docerina-ui/src/component/clients.js, docerina-ui/src/component/method.js, docerina-ui/src/component/methodTable.js, gradle.properties
Changes have been made from ballerina-lang side to add resource kind in api-docs.json file when we are using `bal doc` command.
This will add the UI for resource methods in API docs generated from `bal doc` command.
https://github.com/ballerina-platform/ballerina-lang/pull/39695
https://github.com/ballerina-platform/ballerina-dev-tools/pull/177
=> Add resource method to API docs UI

docerina-ui/src/component/clients.js, docerina-ui/src/component/method.js, docerina-ui/src/component/methodTable.js, gradle.properties
Changes have been made from ballerina-lang side to add resource kind in api-docs.json file when we are using `bal doc` command.
This will add the UI for resource methods in API docs generated from `bal doc` command.
https://github.com/ballerina-platform/ballerina-lang/pull/39695
https://github.com/ballerina-platform/ballerina-dev-tools/pull/176
=> [2201.3.x] Add resource method to API docs UI

docerina-ui/src/component/clients.js, docerina-ui/src/component/method.js, docerina-ui/src/component/methodTable.js, gradle.properties
Changes have been made from ballerina-lang side to add resource kind in api-docs.json file when we are using `bal doc` command.
This will add the UI for resource methods in API docs generated from `bal doc` command.
https://github.com/ballerina-platform/ballerina-lang/pull/39695
https://github.com/ballerina-platform/ballerina-dev-tools/pull/177
=> [2201.4.x] Add resource method to API docs UI

architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/architecturemodelgenerator/core/generators/entity/EntityModelGenerator.java, architecture-model-generator/modules/architecture-model-generator-core/src/test/resources/ballerina/type_gen_simple/types.bal, architecture-model-generator/modules/architecture-model-generator-core/src/test/resources/results/type_gen_sample.json
> $title.
Fixes: #254
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …
=> Fix model generation failure with defaultable record field

gradle.properties
=> Update Ballerina-Lang and Dependency versions to stable versions

flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/AvailableNodesGenerator.java, flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/NodeTemplateGenerator.java, flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/AvailableNode.java, flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/Category.java, flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/FlowNode.java, flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/Item.java, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/java/io/ballerina/flowmodelgenerator/extension/AvailableNodesTest.java, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/simple.json
The PR introduces categories to the `getAvailableNode` API, using a builder pattern to provide available nodes based on cursor position.
1. Initially, a root category is created with common available nodes applicable at any instance. This is generated once during the construction of the object.
2. Depending on the context, the builder can traverse nested categories and add the corresponding node to the relevant category.
=> Add categories to the `getAvailableNodes` API

flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/TypesGenerator.java, flow-model-generator/modules/flow-model-generator-ls-extension/src/main/java/io/ballerina/flowmodelgenerator/extension/ExpressionEditorService.java, flow-model-generator/modules/flow-model-generator-ls-extension/src/main/java/io/ballerina/flowmodelgenerator/extension/response/ExpressionEditorTypeResponse.java, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/java/io/ballerina/flowmodelgenerator/extension/ExpressionEditorTypesTest.java, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/testng.xml, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/config/config1.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/config/config2.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/source/data_mapper/Ballerina.toml, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/source/data_mapper/data_mappings.bal, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/source/data_mapper/main.bal, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/source/data_mapper/service.bal, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/source/data_mapper/types.bal
Using the completions API to get visible types can be inconsistent and challenging. To address this, the `expressionEditor/types` API is introduced to fetch the visible types for the specified cursor position.
=> Provide an LS API to retrieve types for a given position

flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/AvailableNodesGenerator.java, flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/ConnectorGenerator.java, flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/FunctionGenerator.java, flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/db/DatabaseManager.java, flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/ActionCall.java, flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/FunctionCall.java, flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/NewConnection.java, flow-model-generator/modules/flow-model-generator-core/src/main/java/module-info.java, flow-model-generator/modules/flow-model-generator-ls-extension/build.gradle
Since SQLite is not bundled with the distribution, the local index does not function with the latest extension. As a temporary measure, a FAT JAR that includes SQLite has been bundled with the LS extension. This workaround should be reversed once the issue detailed in https://github.com/ballerina-platform/ballerina-distribution/issues/5811 is resolved.
=> Include the fat JAR of the LS extension

flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/FunctionGenerator.java, flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/db/DatabaseManager.java, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/get_functions/config/custom_default.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/get_functions/config/default.json
=> Remove connections and action calls from the default functions list

flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/NodeTemplateGenerator.java, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/data_mapper-main.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/data_mapper-service.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/variable.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/source/data_mapper/main.bal
Since variable names are generated for each request, the cache is returning values from the previous request. This causes the "variable already declared" diagnostic in subsequent requests.
=> Remove the node template cache

flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/ErrorHandlerGenerator.java, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/error_handler_generator/config/error.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/error_handler_generator/config/single.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/error_handler_generator/source/error.bal, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/error_handler_generator/source/single.bal
When the error handler cannot return a non-error value, a diagnostic is generated due to a function signature mismatch. To address this, the error handler will default to returning the added error. Users are responsible for making any necessary adjustments thereafter.
=> Modify the function signature if it lacks the error type

flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/ErrorHandlerGenerator.java, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/java/io/ballerina/flowmodelgenerator/extension/ErrorHandlerGeneratorTest.java, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/error_handler_generator/config/mapping.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/error_handler_generator/source/mapping.bal
$title as expression-bodied functions serve as simple data mappings, making global error handlers unnecessary.
=> Avoid adding error handlers to expression-bodied functions

.github/workflows/build-master.yml, .github/workflows/daily-build.yml, .github/workflows/publish-release.yml, .github/workflows/pull-request.yml
This PR addresses the following changes:
1. Remove building of Testerina and Docerina from the `pull-request` build, since these tools haven't been updated recently and the npm build isn't necessary for other extensions.
2. Set up Ballerina in other workflows, as it's required for building the flow model extension.
=> Update the Github workflows

flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/ExpressionEditorContext.java, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/completions/config/proj1.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/completions/config/proj2.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/completions/config/proj3.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagnostics/config/variable1.json
For cases such as the config variables, the statement is injected to the module level, and an assignment statement like`_ = 12`is invalid. Hence, adding the type`var`if the type is not specific in the provided node.
=> Add the `var` type descriptor to the default statement in the expression editor

flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/ExpressionEditorContext.java, flow-model-generator/modules/flow-model-generator-ls-extension/src/main/java/io/ballerina/flowmodelgenerator/extension/ExpressionEditorService.java, flow-model-generator/modules/flow-model-generator-ls-extension/src/main/java/io/ballerina/flowmodelgenerator/extension/request/FunctionCallTemplateRequest.java, flow-model-generator/modules/flow-model-generator-ls-extension/src/main/java/io/ballerina/flowmodelgenerator/extension/response/FunctionCallTemplateResponse.java, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/java/io/ballerina/flowmodelgenerator/extension/FunctionCallTemplateTest.java, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_call_template/config/config1.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_call_template/config/config2.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_call_template/config/config3.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_call_template/config/config4.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_call_template/source/source.bal, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/testng.xml
This PR implements the generation of function call text when a user selects a function from the helper pane. It handles both already imported and not-yet-imported functions.
- **Function Call Generation:** Generates the correct function call text based on whether the function is currently available, imported, or available for import.
- **Import Handling:** Automatically adds necessary import statements to the shadowed project if a selected function is not already imported.
- **Request/Response:**
- Request: `filepath`, `codedata`, and `kind` (current, import, available).
- Response: A string `template` representing the function call template.
=> Implement a LS API to the generate function call template

flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/AvailableNodesGenerator.java, flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/CodeAnalyzer.java, flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/FunctionGenerator.java, flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/NodeBuilder.java, flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/NodeKind.java, flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/DataMapperCallBuilder.java, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/connector1.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/connector2.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/force_assign.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/foreach1.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/function1.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/function2.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/function3.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/lock1.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/match1.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/match2.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/method1.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/on_fail_clause1.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/resource_connector.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/transaction1.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/transaction2.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/while1.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/data_mapper1.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/diagnostics4.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/get_functions/config/custom_default.json
=> Add new node to represent data mapping function calls

flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/AvailableNodesGenerator.java, flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/CodeAnalyzer.java, flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/StartBuilder.java, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/connector1.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/connector2.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/force_assign.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/foreach1.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/function1.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/function2.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/function3.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/lock1.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/match1.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/match2.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/method1.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/on_fail_clause1.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/resource_connector.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/transaction1.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/transaction2.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/while1.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/start1.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/start2.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/wait1.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/wait2.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/wait9.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/start.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/start.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/start1.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/start2.json
=> Enable the disabled nodes in the node palette

service-model-generator/modules/service-model-generator-ls-extension/src/main/java/io/ballerina/servicemodelgenerator/extension/ServiceModelGeneratorConstants.java, service-model-generator/modules/service-model-generator-ls-extension/src/main/java/io/ballerina/servicemodelgenerator/extension/ServiceModelGeneratorService.java, service-model-generator/modules/service-model-generator-ls-extension/src/main/java/io/ballerina/servicemodelgenerator/extension/Utils.java, service-model-generator/modules/service-model-generator-ls-extension/src/main/java/io/ballerina/servicemodelgenerator/extension/response/ListenerDiscoveryResponse.java, service-model-generator/modules/service-model-generator-ls-extension/src/test/java/io/ballerina/servicemodelgenerator/extension/ServiceModelAPITests.java, service-model-generator/modules/service-model-generator-ls-extension/src/test/resources/get_sm_from_source/config/http_service_with_anonymous_listener.json, service-model-generator/modules/service-model-generator-ls-extension/src/test/resources/get_sm_from_source/config/http_service_with_global_listener.json, service-model-generator/modules/service-model-generator-ls-extension/src/test/resources/get_sm_from_source/config/http_service_with_multiple_listeners.json, service-model-generator/modules/service-model-generator-ls-extension/src/test/resources/get_sm_from_source/config/http_service_with_single_listener.json
$subject
Following things were fixed with this PR
- Populate default:httpListener for listener discovery list
- If an anonymous Listener is attached to a service show the anonymous Listener in the Service edit form
- Use the default:httpListener as the first choice among http Listeners
- Update the http parameter type http resources
=> Fix several issues in the http service designer form

flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/TypesManager.java, flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/utils/TypeTransformer.java, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/get_service_class3.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/update_record_type1.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/update_record_type2.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/update_record_type3.json
* Add a new `createCodeSnippet` method to handle different types of node kinds, replacing the previous logic for generating code snippets.
* Fix not getting the line range for the whole definition node
* Set the `name` property instead of `accessor` for remote function
=> Fix getting whole range when modifying types

flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/DataMapManager.java, flow-model-generator/modules/flow-model-generator-ls-extension/src/main/java/io/ballerina/flowmodelgenerator/extension/DataMapperService.java
$subject
Fixes https://github.com/wso2-enterprise/eggplant-project/issues/532
=> Get semantic model when it is used

flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/DataMapManager.java, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/java/io/ballerina/flowmodelgenerator/extension/DataMappingAddElementTest.java, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/data_mapper_add_element/config/variable10.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/data_mapper_add_element/config/variable7.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/data_mapper_add_element/config/variable8.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/data_mapper_add_element/config/variable9.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/data_mapper_add_element/source/variable5.bal
=> Refactor add elements functionality in datamapping

flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/VisibleVariableTypesGenerator.java, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/visible_variable_types/config/config1.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/visible_variable_types/config/config2.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/visible_variable_types/source/data_mapper/service.bal
The changes add support for Path Parameters in the expression editor helper pane, allowing it to handle both regular path parameters (like [string user]) and rest-type path parameters (like [int... val]) alongside existing variable categories.
=> Add support for path parameters in variable types

flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/DiagnosticHandler.java, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/diagnostics5.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/source/diagnostics/automation.bal, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/source/diagnostics/functions.bal
The PR modifies the diagnostic handler to skip the current diagnostic if it exists in a different file
=> Fix the issue where irrelevant diagnosis are shown in nodes

flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/CodeAnalyzer.java, flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/SuggestedModelGenerator.java, flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/TypeCompletionItemBuilder.java, flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/TypesGenerator.java, flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/FailBuilder.java, flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/PanicBuilder.java, flow-model-generator/modules/flow-model-generator-ls-extension/src/main/java/io/ballerina/flowmodelgenerator/extension/ExpressionEditorService.java, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/java/io/ballerina/flowmodelgenerator/extension/ExpressionEditorCompletionTest.java, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/java/io/ballerina/flowmodelgenerator/extension/ExpressionEditorTypesTest.java, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/config/config1.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/config/config2.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/config/config3.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/config/config4.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/source/data_mapper/types.bal, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/source/graphql/Ballerina.toml, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/source/graphql/graphql_class.bal, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/source/graphql/graphql_service.bal, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/source/graphql/main.bal, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/source/graphql/records.bal, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/source/graphql/types.bal
$title with the following changes:
- Instead of returning only type names, it now provides full CompletionItem objects containing details like kind, documentation, and insert text.
- We are using the `TypeCompletionItemBuilder` in the language-server core to generate the type completion item. This should be refactored later to reuse the implementation.
- Extended the completions to include enums and classes.
=> Change the return type of the `expressionEditor/types` API

flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/TypesGenerator.java, flow-model-generator/modules/flow-model-generator-ls-extension/src/main/java/io/ballerina/flowmodelgenerator/extension/ExpressionEditorService.java, flow-model-generator/modules/flow-model-generator-ls-extension/src/main/java/io/ballerina/flowmodelgenerator/extension/request/ExpressionEditorTypesRequest.java, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/java/io/ballerina/flowmodelgenerator/extension/ExpressionEditorTypesTest.java, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/config/config1.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/config/config2.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/config/config3.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/config/config4.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/config/config5.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/config/config6.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/config/config7.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/config/config8.json
The completions are now filtered based on the type constraint attached to the respective type property in the form field. If there is no type constraint or if the constraint is invalid, all type completions are presented. 
Please note that the type constraint currently only handles built-in types. This means it works for data mapping forms, configurable forms, and dependable types forms. The implementation needs to be extended to support user-defined and module type constraints, which require fetching the type symbol from the semantic model.
=> Consider the type constraint when providing the type completions

flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/VisibleVariableTypesGenerator.java, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/visible_variable_types/config/config1.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/visible_variable_types/config/config2.json
The `visibileVariableTypes` API is modified to ignore empty categories, and only provide results with categories that have at least one item
=> Remove unused categories from the helper pane

flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/function_call-io-fileReadCsv.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/function_call-io-println.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/function_call-json-parseString.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/function_call-json-toJson.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/function_call-log-printInfo.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/function_call-time-utcFromCivil.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/method_call_redis_close.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/new_connection-covid.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/new_connection-docusign.dsadmin.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/new_connection-http.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/new_connection-redis.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/new_connection-snowflake.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/remote_action_call-covid-getStatusByCountry.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/remote_action_call-http-get.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/remote_action_call-http-post.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/remote_action_call-mysql-query.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/remote_action_call-mysql-queryRow.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/remote_action_call-redis-get.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/remote_action_call-redis-set.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/remote_action_call-snowflake-query.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/resource_action_call-docusign.dsadmin-get.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/resource_action_call-github.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/resource_action_call-http-get.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/function_call-io-fileReadCsv.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/function_call-io-println.json, flow-model-generator/modules/flow-model-index-generator/src/main/java/io/ballerina/indexgenerator/IndexGenerator.java, model-generator-commons/src/main/java/io/ballerina/modelgenerator/commons/FunctionDataBuilder.java
The current implementation does not handle complex structures where type parameters are nested under structured type symbols. The PR fixes this by visiting the member types until finding the leaf member type.
=> Improve support for type parameter recognition

flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/EnclosedNodeFinder.java, flow-model-generator/modules/flow-model-generator-ls-extension/src/main/java/io/ballerina/flowmodelgenerator/extension/FlowModelGeneratorService.java, flow-model-generator/modules/flow-model-generator-ls-extension/src/main/java/io/ballerina/flowmodelgenerator/extension/request/EnclosedFuncDefRequest.java, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/java/io/ballerina/flowmodelgenerator/extension/GetEnclosedFunctionDefTest.java, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/get_enclosed_func_def/config/current_package_ref_1.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/get_enclosed_func_def/config/current_package_ref_2.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/get_enclosed_func_def/config/current_package_ref_3.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/get_enclosed_func_def/config/service1.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/get_enclosed_func_def/config/service2.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/get_enclosed_func_def/config/service3.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/get_enclosed_func_def/config/service4.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/get_enclosed_func_def/config/service5.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/get_enclosed_func_def/config/service6.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/get_enclosed_func_def/config/service7.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/get_enclosed_func_def/source/proj_1/graphql_service.bal
When the `findClass` parameter is true, the function returns the class definition range; otherwise, it returns the function definition range.
=> Add support for finding class and service definitions in the `getEnclosedFunctionDef`

flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/search/config/connectors/salesforce.json, model-generator-commons/src/main/java/io/ballerina/modelgenerator/commons/SearchDatabaseManager.java
Currently, the system drops results when it finds the keyword "or". This change ensures that the word is only matched when it appears as a separate term.
=> Fix the sanitization of the search match query

flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/type/RecordValueGenerator.java, model-generator-commons/src/main/java/io/ballerina/modelgenerator/commons/ServiceDatabaseManager.java, service-model-generator/modules/service-model-generator-ls-extension/src/main/java/io/ballerina/servicemodelgenerator/extension/ServiceModelGeneratorConstants.java, service-model-generator/modules/service-model-generator-ls-extension/src/main/java/io/ballerina/servicemodelgenerator/extension/ServiceModelGeneratorService.java, service-model-generator/modules/service-model-generator-ls-extension/src/main/java/io/ballerina/servicemodelgenerator/extension/model/Function.java, service-model-generator/modules/service-model-generator-ls-extension/src/main/java/io/ballerina/servicemodelgenerator/extension/model/Parameter.java, service-model-generator/modules/service-model-generator-ls-extension/src/main/java/io/ballerina/servicemodelgenerator/extension/model/PropertyTypeMemberInfo.java, service-model-generator/modules/service-model-generator-ls-extension/src/main/java/io/ballerina/servicemodelgenerator/extension/model/Value.java, service-model-generator/modules/service-model-generator-ls-extension/src/main/java/io/ballerina/servicemodelgenerator/extension/util/ListenerDeclAnalyzer.java, service-model-generator/modules/service-model-generator-ls-extension/src/main/java/io/ballerina/servicemodelgenerator/extension/util/ListenerUtil.java, service-model-generator/modules/service-model-generator-ls-extension/src/main/java/io/ballerina/servicemodelgenerator/extension/util/ServiceClassUtil.java, service-model-generator/modules/service-model-generator-ls-extension/src/main/java/io/ballerina/servicemodelgenerator/extension/util/Utils.java, service-model-generator/modules/service-model-generator-ls-extension/src/main/resources/services/http.json, service-model-generator/modules/service-model-generator-ls-extension/src/test/java/io/ballerina/servicemodelgenerator/extension/GetServiceModelFromSourceTest.java, service-model-generator/modules/service-model-generator-ls-extension/src/test/resources/get_listener_model/config/graphql_listener_model.json, service-model-generator/modules/service-model-generator-ls-extension/src/test/resources/get_listener_model/config/http_listener_model.json, service-model-generator/modules/service-model-generator-ls-extension/src/test/resources/get_listener_model/config/kafka_listener_model.json, service-model-generator/modules/service-model-generator-ls-extension/src/test/resources/get_sm_from_source/config/graphql_service_with_single_listener.json, service-model-generator/modules/service-model-generator-ls-extension/src/test/resources/get_sm_from_source/config/http_service_with_anonymous_listener.json, service-model-generator/modules/service-model-generator-ls-extension/src/test/resources/get_sm_from_source/config/http_service_with_global_listener.json, service-model-generator/modules/service-model-generator-ls-extension/src/test/resources/get_sm_from_source/config/http_service_with_multiple_listeners.json, service-model-generator/modules/service-model-generator-ls-extension/src/test/resources/get_sm_from_source/config/http_service_with_single_listener.json, service-model-generator/modules/service-model-generator-ls-extension/src/test/resources/listener_from_source/config/listener_from_source_1.json, service-model-generator/modules/service-model-generator-ls-extension/src/test/resources/listener_from_source/config/listener_from_source_2.json, service-model-generator/modules/service-model-generator-ls-extension/src/test/resources/listener_from_source/config/listener_from_source_3.json, service-model-generator/modules/service-model-generator-ls-extension/src/test/resources/listener_from_source/config/listener_from_source_4.json
$subject
This PR fixes following things.
1. Remove init function gen for http service creation
2. Add a return statement to greetings function in http service creation
https://github.com/user-attachments/assets/38a334d7-39a7-4c0f-8d09-7590445784c6
3. Show port information of the default listener
4. Fix few graphql forms metadata
5. Support record value editing for Listener forms
=> Fix several usability issues in service designer

build.gradle, flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/SourceBuilder.java, flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/NewConnectionBuilder.java, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/new_connection-mssql.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/new_connection-mysql.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/new_connection-oracledb.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/new_connection-postgresql.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/new_connection-mssql.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/new_connection-mysql-local.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/new_connection-mysql.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/new_connection-oracledb.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/new_connection-postgresql.json
The default driver is automatically added for MySQL, MSSQL, OracleDB, and PostgreSQL modules, completing the e2e flow for database querying.
=> Add the driver import for database modules

flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/TypesGenerator.java, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/config/config1.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/config/config2.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/config/config4.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/config/config5.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/config/config6.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/config/config7.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/config/config9.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/config/non_existence.json
The initialization should happen once upon the first request. This PR ensures that the initialization is concurrency-safe.
=> Make the type generator concurrency-safe

flow-model-generator/modules/flow-model-generator-ls-extension/src/main/java/io/ballerina/flowmodelgenerator/extension/ExpressionEditorService.java, flow-model-generator/modules/flow-model-generator-ls-extension/src/main/java/io/ballerina/flowmodelgenerator/extension/request/FunctionCallTemplateRequest.java, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/java/io/ballerina/flowmodelgenerator/extension/FunctionCallTemplateTest.java, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_call_template/config/type1.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_call_template/config/type2.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_call_template/source/source.bal
This extends the same implementation of the function browser to the type browser as well.
**NOTE**: This is a temporary solution until the API is properly revamped. Since the correct implementation breaks the whole API, this is introduced as a workaround to work with the existing API.
=> Support type templates in function call templates

flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/CodeAnalyzer.java, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/method_call1.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/method_call_time.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/source/method_call_time.bal
The current implementation renders a custom expression if it cannot determine the expression. With this change, it defaults to the variable node if a type binding pattern node exists.
Related to https://github.com/wso2/product-ballerina-integrator/issues/48
=> Render the variable node if the expression cannot be derived

flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/SourceBuilder.java, flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/DataMapperBuilder.java, flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/DataMapperDefinitionBuilder.java, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/data_mapper_def1.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/data_mapper_def2.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/data_mapper_def3.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/data_mapper_def4.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/data_mapper_def5.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/data_mapper-main.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/data_mapper-service.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/data_mapper1.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/data_mapper_definition6.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/data_mapper_definition7.json, gradle.properties
The PR addresses the following changes:
1. Restricts to only allow subtypes of JSON values in the type constraint, so users won't see unsupported types in the completions.
2. Allow saving primitive types in the data mapper
Fixes https://github.com/wso2/product-ballerina-integrator/issues/17
Fixes https://github.com/wso2/product-ballerina-integrator/issues/96
=> Improve the data mapper form

service-model-generator/modules/service-model-generator-ls-extension/src/main/java/io/ballerina/servicemodelgenerator/extension/OpenApiServiceGenerator.java, service-model-generator/modules/service-model-generator-ls-extension/src/main/java/io/ballerina/servicemodelgenerator/extension/ServiceModelGeneratorConstants.java, service-model-generator/modules/service-model-generator-ls-extension/src/main/java/io/ballerina/servicemodelgenerator/extension/ServiceModelGeneratorService.java, service-model-generator/modules/service-model-generator-ls-extension/src/main/java/io/ballerina/servicemodelgenerator/extension/util/ListenerUtil.java, service-model-generator/modules/service-model-generator-ls-extension/src/test/resources/add_service/config/add_graphql_service_2.json, service-model-generator/modules/service-model-generator-ls-extension/src/test/resources/get_service_model/config/graphql_service_model.json, service-model-generator/modules/service-model-generator-ls-extension/src/test/resources/get_service_model/config/kafka_service_model_2.json, service-model-generator/modules/service-model-generator-ls-extension/src/test/resources/get_service_model/config/rabbitmq_service_model.json, service-model-generator/modules/service-model-generator-ls-extension/src/test/resources/get_service_model/config/tcp_service_model.json, service-model-generator/modules/service-model-generator-ls-extension/src/test/resources/get_sm_from_source/config/kafka_service_model.json
$subject
Fixes [#issue](https://github.com/wso2/product-ballerina-integrator/issues/99)
Once use select the `(+) Create and use a %s listener with default configurations` option we will create a default listener for selected service type and attach the created listener to the service.
Here are the listener decelerations for each listener
```ballerina
listener http:Listener httpDefaultListener = http:getDefaultListener();
listener graphql:Listener graphqlDefaultListener = new (listenTo = 8080);
listener tcp:Listener tcpDefaultListener = new (localPort = 8080);
listener github:Listener githubDefaultListener = new ();
listener salesforce:Listener salesforceDefaultListener = new (auth = {username: "", password: ""});
listener asb:Listener asbDefaultListener = new (connectionString = "", …
```
=> Support creating listener with default configurations for all listener types

flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/expressioneditor/services/TypeDiagnosticRequest.java, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagnostics/config/types15.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagnostics/config/types16.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagnostics/config/types17.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagnostics/config/types18.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagnostics/config/types19.json
Until this is implemented as a flag, the diagnostic is removed to allow users to save such nodes
Fixes https://github.com/wso2/product-ballerina-integrator/issues/130
The proper solution is tracked with https://github.com/wso2/product-ballerina-integrator/issues/150
=> Remove the diagnostic output for read-only field types in the type editor

flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/TypesGenerator.java, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/config/config11.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/config/config12.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/config/config5.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/config/config6.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/config/config7.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/config/config8.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/config/non_existence.json
$title since having two types with the same label may confuse users.
Fixes https://github.com/wso2/product-ballerina-integrator/issues/225
=> Remove duplicate type completions from the `expressionEditor/types`

.github/workflows/build-master.yml, .github/workflows/pull-request.yml
$title to avoid outdated runs for the previous commits.
=> Add concurrency settings to build workflows

flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/AutomationBuilder.java, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/automation_definition4.json
$title when generating a new automation without the return error, since there is no logging.
Fixes https://github.com/wso2/ballerina-vscode/issues/594
=> Remove unused log imports when generating source code for automations

flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/expressioneditor/services/LvExpressionDiagnosticRequest.java, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagnostics/config/assign9.json
$title as the variable can be ignored by the user.
Fixes https://github.com/wso2/product-ballerina-integrator/issues/290
=> Allow underscore `_` in variable names for the assign node

flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/VisibleVariableTypesGenerator.java, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/visible_variable_types/config/config1.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/visible_variable_types/config/config2.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/visible_variable_types/config/config3.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/visible_variable_types/config/non_existence.json
$subject
Fixes [OOM occurs when trying to return a value using BI](https://github.com/wso2-enterprise/internal-support-ballerina/issues/979)
The `visibleVariableTypes` API is used in the expression editor's helper pane, where we display visible variable symbols grouped under different categories. Currently, this helper pane only uses the `Type` object to show the type name alongside each variable.
However, the existing implementation of the `Type` object includes additional type information, which is unnecessary for this use case and can lead to performance issues, as noted in [this comment](https://github.com/wso2-enterprise/internal-support-ballerina/issues/979#issuecomment-2894468121).
With this PR, we simplify the response by including only the type name in the `Type` object …
=> [2201.12.x] Include only the type name in the Type object for visibleVariableTypes API variable types

flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/AgentsGenerator.java, flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/SourceBuilder.java, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/java/io/ballerina/flowmodelgenerator/extension/agentsmanager/GenToolsTest.java, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/config/remote_action_tool6.json
$subject
Fixes https://github.com/wso2/product-ballerina-integrator/issues/302
Duplicate PR to the 2201.12.x branch for https://github.com/ballerina-platform/ballerina-dev-tools/pull/861
=> [2201.12.x] Fix issues in AI tool description generation

flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/AgentsGenerator.java, flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/AvailableNodesGenerator.java, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/config/available_agents.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/config/get_all_agents.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/config/get_all_memory_managers.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/config/get_all_models.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/caller.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/connector1.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/connector2.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/connector3.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/force_assign.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/foreach1.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/function1.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/function2.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/function3.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/inside_nested_foreach.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/lock1.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/match1.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/match2.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/method1.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/on_fail_clause1.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/resource_connector.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/transaction1.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/transaction2.json, flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/while1.json
$subject
Fixes  [Agent manager block is not rendering in BI](https://github.com/wso2/product-ballerina-integrator/issues/474)
https://github.com/user-attachments/assets/51b18914-13ff-4749-8245-4ab934d1d798
=> Fix issue with rendering agent nodes via node template
