ballerina-platform/ballerina-dev-tools

- docerina-ui/src/App.js
- docerina-ui/src/Module.js
- docerina-ui/src/Package.js
- docerina-ui/src/component/helper.js
- docerina-ui/src/component/layout.js
- docerina-ui/src/component/moduleview.js
- docerina-ui/src/component/packageview.js
- docerina-ui/src/component/searchlist.js
- docerina-ui/src/component/sidebar.js
- docerina-ui/src/component/types.js
> Improve doc ui

- docerina-ui/src/component/fields.js
> Fix spacing issue

- docerina-ui/public/html-template-resources/styles/css/styles.css
- docerina-ui/src/component/initMethod.js
Fixes an issue where the react app crashes due to dom manipulation by Prism.
> Fix ui crashing due to prism

- docerina-ui/public/html-template-resources/styles/css/styles.css
Make styles consistent with Prism highlighter
> Make styles consistent with Prism

- docerina-ui/package.json
- gradle.properties
- testerina-report-tools/package.json
> Release 0.8.0

- docerina-ui/package.json
- docerina-ui/src/component/initMethod.js
- gradle.properties
- testerina-report-tools/package.json
>- Fixes an issue where, empty parameters in init method causes the React app to crash.
> Fix init method

- docerina-ui/package.json
- docerina-ui/public/html-template-resources/styles/css/styles.css
- docerina-ui/src/Module.js
- docerina-ui/src/Package.js
- docerina-ui/src/component/abstractobjects.js
- docerina-ui/src/component/annotations.js
- docerina-ui/src/component/classes.js
- docerina-ui/src/component/clients.js
- docerina-ui/src/component/constants.js
- docerina-ui/src/component/constructlist.js
- docerina-ui/src/component/errors.js
- docerina-ui/src/component/functions.js
- docerina-ui/src/component/helper.js
- docerina-ui/src/component/initMethod.js
- docerina-ui/src/component/layout.js
- docerina-ui/src/component/listeners.js
- docerina-ui/src/component/method.js
- docerina-ui/src/component/moduleview.js
- docerina-ui/src/component/record.js
- docerina-ui/src/component/sidebar.js
- docerina-ui/src/component/types.js
- gradle.properties
- testerina-report-tools/package.json
>- Fix scroll issue in Firefox
>- Fix font size in version picker
>- Make version picker link to relevant old module pages
>- Add highlighting a div after anchor click
>- Improve react code
> Fix scroll, improve react code

- .github/workflows/publish-release.yml
- docerina-ui/package.json
- gradle.properties
- testerina-report-tools/package.json
> Sync main branch with Release 0.8.4

- docerina-ui/src/component/fields.js
- docerina-ui/src/component/functions.js
- docerina-ui/src/component/helper.js
- docerina-ui/src/component/method.js
- docerina-ui/src/component/methodTable.js
Related to https://github.com/ballerina-platform/ballerina-lang/pull/27811
> Add support for type inclusion, typedesc and bug fixes

- docerina-ui/src/component/classes.js
- docerina-ui/src/component/clients.js
- docerina-ui/src/component/codeblock.js
- docerina-ui/src/component/fields.js
- docerina-ui/src/component/helper.js
- docerina-ui/src/component/listeners.js
>- Removes unnecessary # in code sections. Temporary fix for: https://github.com/ballerina-platform/ballerina-lang/issues/27658
>- Fix browser back button skipping pages in some instances.
>- Remove type details of fields coming from type inclusions.
>- Add readonly and isolated support for classes. (Related PR: https://github.com/ballerina-platform/ballerina-lang/pull/27907)
>- Add readonly support for record fields
> Docerina improvements

- docerina-ui/src/Module.js
- docerina-ui/src/Package.js
- docerina-ui/src/component/helper.js
- docerina-ui/src/component/layout.js
- docerina-ui/src/component/notfound.js
- docerina-ui/src/component/sidebar.js
> Add 404 page

- docerina-ui/src/component/codeblock.js
> Fix code block

- docerina-ui/src/component/constructlist.js
> Fix construct links (mobile)

- docerina-ui/src/Module.js
- docerina-ui/src/component/layout.js
- docerina-ui/src/component/packageview.js
- docerina-ui/src/component/searchlist.js
- docerina-ui/src/component/sidebar.js
>- Add module list to sidebar
>- Add modules to breadcrumb
> Add module list sidebar and breadcrumb

- docerina-ui/src/component/packageview.js
> Fix linking when package names have fullstops in their names

- docerina-ui/public/html-template-resources/styles/css/styles.css
- docerina-ui/src/component/codeblock.js
- docerina-ui/src/component/enum.js
- docerina-ui/src/component/functions.js
- docerina-ui/src/component/initMethod.js
- docerina-ui/src/component/moduleview.js
>- Fix enum names overflowing in table
>- Fix broken links caused by modules/pacakges that have `.` in their names
>- Fix codeblcoks in io mdoule
> Fix enum table overflow and links

- docerina-ui/src/component/abstractobjects.js
- docerina-ui/src/component/annotations.js
- docerina-ui/src/component/classes.js
- docerina-ui/src/component/clients.js
- docerina-ui/src/component/constructlist.js
- docerina-ui/src/component/enum.js
- docerina-ui/src/component/layout.js
- docerina-ui/src/component/listeners.js
- docerina-ui/src/component/methodTable.js
- docerina-ui/src/component/notfound.js
- docerina-ui/src/component/record.js
> Change to match next app

- docerina-ui/src/component/layout.js
Update version picker to reflect bio changes.
> Update version picker

- docerina-ui/src/component/layout.js
Change breaadcrumb for ballerinax
> Change breaadcrumb for ballerinax

- docerina-ui/src/component/helper.js
- docerina-ui/src/component/layout.js
- docerina-ui/src/component/moduleview.js
- docerina-ui/src/component/packageindex.js
- docerina-ui/src/component/sidebar.js
- docerina-ui/src/styles.css
> Add UI Changes

- docerina-ui/src/Module.js
- docerina-ui/src/component/helper.js
- docerina-ui/src/component/moduleview.js
- docerina-ui/src/component/objecttypes.js
- docerina-ui/src/component/searchlist.js
- docerina-ui/src/component/sidebar.js
React Changes related to https://github.com/ballerina-platform/ballerina-lang/pull/28757
> Change abstract objects to object types

- docerina-ui/src/App.js
- gradle.properties
> Change api doc source

- docerina-ui/src/App.js
- docerina-ui/src/component/builtin.js
- docerina-ui/src/component/fields.js
Fixes https://github.com/ballerina-platform/ballerina-lang/issues/28261
and broken anchors in bultin type page
> Fix anchor links

- docerina-ui/src/component/builtin.js
- docerina-ui/src/component/helper.js
- docerina-ui/src/component/keyword.js
- docerina-ui/src/component/packageindex.js
> Alpha3 improvements

- docerina-ui/src/component/helper.js
- docerina-ui/src/component/objecttypes.js
- docerina-ui/src/component/record.js
- docerina-ui/src/component/searchlist.js
Add react code related to: https://github.com/ballerina-platform/ballerina-lang/pull/29639
> Alpha4 changes

- docerina-ui/src/component/layout.js
> Fix builtin links

- docerina-ui/src/component/annotations.js
- docerina-ui/src/component/errors.js
- docerina-ui/src/component/fields.js
- docerina-ui/src/component/functions.js
- docerina-ui/src/component/layout.js
- docerina-ui/src/component/listeners.js
- docerina-ui/src/component/methodTable.js
- docerina-ui/src/component/moduleindex.js
- docerina-ui/src/component/moduleview.js
- docerina-ui/src/component/objecttypes.js
- docerina-ui/src/component/record.js
- docerina-ui/src/component/sidebar.js
- docerina-ui/src/styles.css
> Fix UI issues

- docerina-ui/src/component/objecttypes.js
> Fixes a bug caused by incorrect variable name.
> Fix incorrect variable name

- docerina-ui/public/content/copy-icon.svg
- docerina-ui/src/component/codeblock.js
- docerina-ui/src/component/searchlist.js
- docerina-ui/src/styles.css
> Add code copy functionality

- docerina-ui/public/content/copy-icon.svg
- docerina-ui/src/component/codeblock.js
- docerina-ui/src/component/moduleindex.js
- docerina-ui/src/styles.css
>- Fixes  copy button appearing over code (https://docs.google.com/document/d/1PBpQYfmuNaQhCNLXbbi87-eDvkuI_sBZwR_wqlcnNUQ/edit?disco=AAAAIjWGlN0)
>- Fixes module version being wrapped in module index
> Fix beta1 ui issues

- docerina-ui/src/Module.js
- docerina-ui/src/component/layout.js
- docerina-ui/src/component/moduleview.js
- docerina-ui/src/component/sidebar.js
- docerina-ui/src/component/types.js
- docerina-ui/src/component/variables.js
Subject
Related PR: https://github.com/ballerina-platform/ballerina-lang/pull/30972
> Add UI support for module varaiables

- docerina-ui/src/__tests__/load_data.test.js
- docerina-ui/src/component/annotations.js
- docerina-ui/src/component/codeblock.js
- docerina-ui/src/component/layout.js
- docerina-ui/src/component/moduleindex.js
- docerina-ui/src/component/sidebar.js
> Sync components with next app

- docerina-ui/src/component/codeblock.js
- docerina-ui/src/component/fields.js
- docerina-ui/src/component/moduleview.js
- docerina-ui/src/styles.css
> Fixes #https://github.com/ballerina-platform/ballerina-dev-tools/issues/126
> UI Changes for https://github.com/ballerina-platform/ballerina-lang/pull/31650/
> And sync with Central Docs UI
> Sync with central docs

- docerina-ui/src/component/moduleindex.js
Add heading to site home page.
> Add heading to site home page.

- testerina-report-tools/package.json
- testerina-report-tools/src/App.css
- testerina-report-tools/src/App.tsx
> $Subject
> Fixes [https://github.com/ballerina-platform/ballerina-lang/issues/31201](url)
After changes applied:
> Make the back button larger in the coverage report

- docerina-ui/src/index.html
> $subject
Fixes https://github.com/ballerina-platform/ballerina-dev-tools/issues/158 …
> Support viewing unicode in API docs

- build.gradle
- testerina-report-tools/build.gradle
> Update the output directories of build artifacts.  …
> Update build artifact output directories

- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/architecturemodelgenerator/core/ProjectDesignConstants.java
- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/architecturemodelgenerator/core/generators/ModelGenerator.java
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/results/reservation_api_model.json
> This PR fixes the issue https://github.com/ballerina-platform/ballerina-lang/issues/39273 …
> Fix invalid path for services and entities resideing in non-default modules

- .github/CODEOWNERS
- architecture-model-generator/modules/architecture-model-generator-core/src/test/java/io/ballerina/architecturemodelgenerator/core/ServiceGeneratorTests.java
- architecture-model-generator/modules/architecture-model-generator-core/src/test/java/io/ballerina/architecturemodelgenerator/core/TestUtils.java
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/java/io/ballerina/architecturemodelgenerator/extension/ArchitectureModelGeneratorServiceTests.java
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/java/io/ballerina/architecturemodelgenerator/extension/TestUtils.java
> This PR intends to fix test cases to work with regardless of std-lib versions …
> Fix test cases to work with regardless of std-lib versions

- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/architecturemodelgenerator/core/ProjectDesignConstants.java
- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/architecturemodelgenerator/core/generators/entity/EntityModelGenerator.java
- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/architecturemodelgenerator/core/generators/entity/nodevisitors/TypeDefinitionNodeVisitor.java
- architecture-model-generator/modules/architecture-model-generator-core/src/test/resources/ballerina/type_gen_simple/types.bal
- architecture-model-generator/modules/architecture-model-generator-core/src/test/resources/results/type_gen_sample.json
> This PR fixes the issue https://github.com/ballerina-platform/ballerina-lang/issues/39299 …
> Improve entity model generator to include constraints for cardinalities

- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/architecturemodelgenerator/core/ComponentModel.java
- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/architecturemodelgenerator/core/ComponentModelBuilder.java
- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/architecturemodelgenerator/core/ProjectDesignConstants.java
> This PR is to update the component-model JSON schema to include the model-version as this would be useful to do updates to the model in the future if required.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief …
> Update Component-Model JSON schema to include model-version

- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/architecturemodelgenerator/core/generators/service/nodevisitors/ActionNodeVisitor.java
> This PR fixes the issue https://github.com/ballerina-platform/ballerina-lang/issues/39196 …
> Fix resource function not getting mapped correctly in architecture design tool

- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/architecturemodelgenerator/core/ComponentModelBuilder.java
- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/architecturemodelgenerator/core/generators/ModelGenerator.java
- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/architecturemodelgenerator/core/generators/entity/EntityModelGenerator.java
- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/architecturemodelgenerator/core/generators/service/ServiceModelGenerator.java
- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/architecturemodelgenerator/core/generators/service/nodevisitors/ActionNodeVisitor.java
- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/architecturemodelgenerator/core/generators/service/nodevisitors/ServiceDeclarationNodeVisitor.java
- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/architecturemodelgenerator/core/generators/service/nodevisitors/ServiceMemberFunctionNodeVisitor.java
- architecture-model-generator/modules/architecture-model-generator-core/src/test/resources/ballerina/single_service_sample/main.bal
- architecture-model-generator/modules/architecture-model-generator-core/src/test/resources/ballerina/single_service_sample/modules/model/AccountModel.bal
- architecture-model-generator/modules/architecture-model-generator-core/src/test/resources/ballerina/single_service_sample/modules/repo/Repo.bal
- architecture-model-generator/modules/architecture-model-generator-core/src/test/resources/ballerina/single_service_sample/modules/service/Service.bal
- architecture-model-generator/modules/architecture-model-generator-core/src/test/resources/results/simple_service_sample.json
> Fixes https://github.com/ballerina-platform/ballerina-lang/issues/39540 …
> Fix Model generation failure with MethodCallExpressionNode

- gradle.properties
> Update the lang and dependency versions

- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/architecturemodelgenerator/core/generators/service/nodevisitors/ActionNodeVisitor.java
- architecture-model-generator/modules/architecture-model-generator-core/src/test/resources/ballerina/single_service_sample/main.bal
- architecture-model-generator/modules/architecture-model-generator-core/src/test/resources/ballerina/single_service_sample/modules/service/Service.bal
- architecture-model-generator/modules/architecture-model-generator-core/src/test/resources/results/simple_service_sample.json
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/results/frontend_service.json
> This is a fix when node visitor causes StackOverflow error when recursive function calls are present and resource interaction duplication when the interaction is created from across modules.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, …
> Fix StackOverFlow Error when recursive functions are visited

- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/java/io/ballerina/architecturemodelgenerator/extension/ArchitectureModelGeneratorServiceTests.java
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/ballerina/microservice_grpc/cart/cart_service.bal
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/ballerina/microservice_grpc/checkout/checkout_service.bal
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/ballerina/microservice_grpc/frontend/rpc.bal
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/ballerina/microservice_grpc/frontend/utils.bal
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/ballerina/reservation_api/modules/seat_allocation_api/utils.bal
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/ballerina/reservation_api/reservation_service.bal
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/results/cart_service.json
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/results/checkout_service.json
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/results/frontend_service.json
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/results/reservation_api_model.json
> Fix Daily-Build test failures

- gradle.properties
> Update graphql version

- gradle.properties
> Update dev-tools repo version for SL update5

- build.gradle
- gradle.properties
> Update dev-tools dependency versions

- build.gradle
- gradle.properties
> Include dependencies that failes to get  resolved.

- gradle.properties
> Update Lang and dependency versions

- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/architecturemodelgenerator/core/ProjectDesignConstants.java
- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/architecturemodelgenerator/core/generators/service/nodevisitors/ActionNodeVisitor.java
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/ballerina/reservation_api/modules/weather_api/Module.md
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/ballerina/reservation_api/modules/weather_api/weather_api.bal
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/ballerina/reservation_api/reservation_service.bal
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/results/reservation_api_model.json
> $title.
Fixes: https://github.com/ballerina-platform/ballerina-dev-tools/issues/194 …
> Fix invalid resourceId with default get method

- gradle.properties
> Update Ballerina Lang version

- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/architecturemodelgenerator/core/generators/GeneratorUtils.java
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/ballerina/reservation_api/main.bal
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/results/reservation_api_model.json
> Fixes: https://github.com/ballerina-platform/ballerina-dev-tools/issues/208 …
> Fix invalid elementLocation for MainEntryPoint annotations

- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/architecturemodelgenerator/core/ProjectDesignConstants.java
- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/architecturemodelgenerator/core/generators/entrypoint/nodevisitors/FunctionEntryPointMemberNodeVisitor.java
- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/architecturemodelgenerator/core/generators/service/nodevisitors/ActionNodeVisitor.java
- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/architecturemodelgenerator/core/generators/service/nodevisitors/ServiceDeclarationNodeVisitor.java
- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/architecturemodelgenerator/core/generators/service/nodevisitors/ServiceMemberFunctionNodeVisitor.java
- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/architecturemodelgenerator/core/model/service/Dependency.java
- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/architecturemodelgenerator/core/model/service/ResourceId.java
- architecture-model-generator/modules/architecture-model-generator-core/src/test/java/io/ballerina/architecturemodelgenerator/core/ServiceGeneratorTests.java
- architecture-model-generator/modules/architecture-model-generator-core/src/test/resources/results/simple_service_sample.json
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/java/io/ballerina/architecturemodelgenerator/extension/ArchitectureModelGeneratorServiceTests.java
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/results/checkout_service.json
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/results/frontend_service.json
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/results/reservation_api_model.json
- This PR is to include a label field with ResourceId. For each interaction and dependency, the resourceId now includes the Label field as well, this is useful to name the end-points from the FrontEnd.
- Initially, Interactions and dependencies were drawn with the support of serviceId and, labeling could also be done for internal services as we preserve the annotations as well in the model. But for the external EPs we don't preserve the annotations, So to give the labeling support for external EPs, for `ResourceId` a new field `serviceLabel` is introduced.
ResourceId - Before
```Ballerina
type ResourceId record {|
string? serviceId;
string action;
string path;
|};
```
ResourceId - Now …
> Include label field for ResourceId from annotations

- graphql-model-generator/modules/graphql-model-generator-core/src/main/java/io/ballerina/graphqlmodelgenerator/core/ModelGenerator.java
- graphql-model-generator/modules/graphql-model-generator-core/src/main/java/io/ballerina/graphqlmodelgenerator/core/ServiceModelGenerator.java
related issue https://github.com/ballerina-platform/ballerina-dev-tools/issues/214 …
> Remove deprecated filepath api and update to new `fileName` from graphql-model-generator

- build.gradle
- gradle.properties
> This PR includes the changes to include few std-lib dependencies which causing test failures.
> Link to the PR for changes to …
> Fix dependency resolving issue

- build.gradle
- gradle.properties
> [1.0.x] Fix dependency resolving issue

- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/java/io/ballerina/architecturemodelgenerator/extension/TestUtils.java
- gradle.properties
> Replace std-lib version string to fix failing testcase

- build.gradle
- gradle.properties
> Update dev-tools dependency timestamped versions

- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/java/io/ballerina/architecturemodelgenerator/extension/PersistERModelGeneratorTests.java
> $title, this is disabled due to the lang changes to be published, once that is made, tests will be enables with amended test results.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc …
> Disable Persist ER Model Generator test cases temporarily

- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/java/io/ballerina/architecturemodelgenerator/extension/PersistERModelGeneratorTests.java
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/results/rainier_er_model.json
- gradle.properties
> $title.
Fixes  #239
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …
> Enable temporarily disabled persist-tests

- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/architecturemodelgenerator/core/diagnostics/ArchitectureModelDiagnostic.java
- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/architecturemodelgenerator/core/diagnostics/ArchitectureModelDiagnosticLocation.java
- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/architecturemodelgenerator/core/diagnostics/DiagnosticLocation.java
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/main/java/io/ballerina/architecturemodelgenerator/extension/persist/PersistERModelGeneratorService.java
- gradle.properties
> $title, so that, even if the model generation completely fails or partially fails, the reason for the failure is already captured that can be shown to the users.
Fixes: #241
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus …
> Include Compilation Diagnostics with Persist Model

- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/architecturemodelgenerator/core/generators/entity/EntityModelGenerator.java
- architecture-model-generator/modules/architecture-model-generator-core/src/test/resources/ballerina/type_gen_simple/main.bal
- architecture-model-generator/modules/architecture-model-generator-core/src/test/resources/results/type_gen_sample.json
> Fix Entity Model generation failure when types are defined in more than one Bal file

- gradle.properties
> Update dev-tools version

- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/ballerina/rainier/Ballerina.toml
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/ballerina/rainier/resources/Ballerina.toml
- build-config/checkstyle/build.gradle
- build.gradle
- docerina-ui/build.gradle
- gradle.properties
- gradle/javaProject.gradle
- gradle/wrapper/gradle-wrapper.properties
- settings.gradle
- spotbugs-exclude.xml
- testerina-report-tools/build.gradle
> Migrate to Java 17

- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/architecturemodelgenerator/core/generators/entity/EntityModelGenerator.java
- architecture-model-generator/modules/architecture-model-generator-core/src/test/resources/ballerina/type_gen_simple/types.bal
- architecture-model-generator/modules/architecture-model-generator-core/src/test/resources/results/type_gen_sample.json
> $title.
Fixes: https://github.com/ballerina-platform/ballerina-dev-tools/issues/254 …
> Fix model generation failure with defaultable record field

- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
> Use Gradle version 7.6.2

- architecture-model-generator/modules/architecture-model-generator-core/src/test/java/io/ballerina/architecturemodelgenerator/core/ServiceGeneratorTests.java
> Disable model gen test

- .github/workflows/build-master.yml
- .github/workflows/daily-build.yml
- .github/workflows/publish-release.yml
- .github/workflows/pull-request.yml
- gradle.properties
- gradle/javaProject.gradle
> Update Java version to 17.0.7 in workflows

- testerina-report-tools/package.json
Fix for :testerina-report-tools:npmInstallTesterinaReportTools 
https://scans.gradle.com/s/6qll42b5z7qjm/console-log?anchor=594&page=1
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc …
> Bump react script version

- .github/workflows/pull-request.yml
> Skip docerina-ui tests

- architecture-model-generator/modules/architecture-model-generator-core/src/test/java/io/ballerina/architecturemodelgenerator/core/TestUtils.java
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/java/io/ballerina/architecturemodelgenerator/extension/TestUtils.java
- gradle.properties
> Update Ballerina lang version and StdLib versions

- gradle.properties
> Update the GraphQL Dependency Version

- gradle.properties
> Update graphql timestamp version

- architecture-model-generator/modules/architecture-model-generator-core/src/test/java/io/ballerina/architecturemodelgenerator/core/ServiceGeneratorTests.java
- architecture-model-generator/modules/architecture-model-generator-core/src/test/java/io/ballerina/architecturemodelgenerator/core/TypeGeneratorTests.java
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/java/io/ballerina/architecturemodelgenerator/extension/ArchitectureModelGeneratorServiceTests.java
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/java/io/ballerina/architecturemodelgenerator/extension/PersistERModelGeneratorTests.java
- graphql-model-generator/modules/graphql-model-generator-ls-extension/src/test/java/io/ballerina/graphqlmodelgenerator/extension/GraphqlModelGeneratorServiceTests.java
> Disable test cases

- gradle.properties
> Bump minor version for 2201.8.0

- .github/workflows/publish-release.yml
> Skip docerina UI tests

- docerina-ui/src/component/layout.js
Update the `Ballerina library` word. …
> Update the `Ballerina library` word

- architecture-model-generator/modules/architecture-model-generator-core/src/test/java/io/ballerina/architecturemodelgenerator/core/ServiceGeneratorTests.java
disable testSingleModuleModelGeneration temporary.
Track in #303 
Reason - https://github.com/ballerina-platform/ballerina-release/actions/runs/6912770475
> disable testSingleModuleModelGeneration temporary

- build.gradle
- worker-model-generator/modules/worker-model-generator-core/src/main/java/io.ballerina.workermodelgenerator.core/analyzer/Analyzer.java
- worker-model-generator/modules/worker-model-generator-core/src/main/java/io.ballerina.workermodelgenerator.core/analyzer/TransformAnalyzer.java
> Sync worker model changes

- gradle.properties
- worker-model-generator/modules/worker-model-generator-core/src/main/java/io.ballerina.workermodelgenerator.core/analyzer/Analyzer.java
- worker-model-generator/modules/worker-model-generator-core/src/main/java/io.ballerina.workermodelgenerator.core/analyzer/CodeBlockAnalyzer.java
- worker-model-generator/modules/worker-model-generator-core/src/main/java/io.ballerina.workermodelgenerator.core/analyzer/TransformAnalyzer.java
- worker-model-generator/modules/worker-model-generator-core/src/main/java/io.ballerina.workermodelgenerator.core/model/properties/CodeBlock.java
- worker-model-generator/modules/worker-model-generator-core/src/main/java/io.ballerina.workermodelgenerator.core/model/properties/NodeProperties.java
- worker-model-generator/modules/worker-model-generator-ls-extension/src/test/java/io/ballerina/workermodelgenerator/extension/ModelGeneratorTest.java
- worker-model-generator/modules/worker-model-generator-ls-extension/src/test/resources/config/alternate_receiver.json
- worker-model-generator/modules/worker-model-generator-ls-extension/src/test/resources/config/body_code_location.json
- worker-model-generator/modules/worker-model-generator-ls-extension/src/test/resources/config/code_block.json
- worker-model-generator/modules/worker-model-generator-ls-extension/src/test/resources/config/hospital_service.json
- worker-model-generator/modules/worker-model-generator-ls-extension/src/test/resources/config/metadata_code_block.json
- worker-model-generator/modules/worker-model-generator-ls-extension/src/test/resources/config/service_orchestration.json
- worker-model-generator/modules/worker-model-generator-ls-extension/src/test/resources/config/simple_project.json
- worker-model-generator/modules/worker-model-generator-ls-extension/src/test/resources/config/simple_switch.json
- worker-model-generator/modules/worker-model-generator-ls-extension/src/test/resources/config/simple_transform.json
- worker-model-generator/modules/worker-model-generator-ls-extension/src/test/resources/config/transform_with_error.json
- worker-model-generator/modules/worker-model-generator-ls-extension/src/test/resources/config/transform_with_input.json
As updated in the model, the `CodeBlock` node is used within the `CodeBlockNode` and the `TransformNode`.
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? no
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
> Add CodeBlock to the model

- architecture-model-generator/modules/architecture-model-generator-core/src/test/java/io/ballerina/architecturemodelgenerator/core/ServiceGeneratorTests.java
- architecture-model-generator/modules/architecture-model-generator-core/src/test/java/io/ballerina/architecturemodelgenerator/core/TypeGeneratorTests.java
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/java/io/ballerina/architecturemodelgenerator/extension/ArchitectureModelGeneratorServiceTests.java
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/java/io/ballerina/architecturemodelgenerator/extension/PersistERModelGeneratorTests.java
> Disable architecture-model-generator Tests Temporarily

- gradle.properties
> [8.x] Update dependencies to stable versions

- graphql-model-generator/modules/graphql-model-generator-ls-extension/src/test/java/io/ballerina/graphqlmodelgenerator/extension/GraphqlModelGeneratorServiceTests.java
The tests were failing in the distribution pipeline https://github.com/ballerina-platform/ballerina-release/actions/runs/8173229932/job/22359729504#step:8:41014.
But this cannot be reproduced locally. 
Therefore the tests are temporary disabled with this pr
> Link(s) to product …
> Temporary disable graphql tests in 8.x branch

- gradle.properties
> Bump the GraphQL version

- testerina-report-tools/src/FileCoverage.tsx
Fixes [issue #41965](https://github.com/ballerina-platform/ballerina-lang/issues/41965#issue-2076021276)
previous report:
report with fix:
> Add horizontal scroll support for Testerina code coverage report

- gradle.properties
- sequence-diagram-model-generator/modules/sequence-diagram-model-generator-core/src/main/java/io/ballerina/sequencemodelgenerator/core/visitors/ActionVisitor.java
> Fix sequence diagram build failure due to syntax change in ballerina-lang

- build.gradle
- docerina-ui/package.json
- gradle.properties
- testerina-report-tools/package.json
> Update the dependency versions to latest timestamps

- gradle.properties
> Update the GraphQL Version

- gradle.properties
> Update dependencies to stable versions

- build.gradle
- docerina-ui/package.json
- gradle.properties
- sequence-diagram-model-generator/modules/sequence-diagram-model-generator-core/src/main/java/io/ballerina/sequencemodelgenerator/core/visitors/ActionVisitor.java
- testerina-report-tools/package.json
- testerina-report-tools/src/FileCoverage.tsx
> Sync flow model with master

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/CodeAnalyzer.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/NodeTemplateGenerator.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/FlowNode.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/Start.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/StartNode.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/start1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/start2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/source/start.bal
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/start.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/start_node1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/start_node2.json
$subject
Part of https://github.com/wso2-enterprise/eggplant-product-management/issues/15
> Support for start node

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/CodeAnalyzer.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/FlowNode.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/NodeBuilder.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/Stop.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/if4.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/lock3.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/stop1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/stop2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/source/stop.bal
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/stop.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/stop0.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/stop1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/stop2.json
> Add Stop node

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/AvailableNodesGenerator.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/CodeAnalyzer.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/FlowNode.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/NodeBuilder.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/Property.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/Foreach.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/simple.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/foreach1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/foreach2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/foreach3.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/foreach4.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/foreach5.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/source/foreach.bal
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/foreach.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/foreach0.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/foreach1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/foreach2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/foreach3.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/foreach4.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/foreach5.json
> Add Foreach node

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/CodeAnalyzer.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/currency_converter1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/new_data5.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/new_data6.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/update_data5.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/source/new_data.bal
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/source/update_data.bal
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/new_data15.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/new_data16.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/new_data17.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/new_data18.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/update_data6.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/update_data7.json
With this change, the following case will be modeled as a new data model.
```ballerina
function testJson(int amount) returns error? {
json newData = {value: check calculate(amount)};
}
```
> Visit mapping and list constructors

- testerina-report-tools/package.json
$ subject
Fixes https://github.com/ballerina-platform/ballerina-dev-tools/issues/378 …
> Specify babel versions in pacakge.json to fix test report build failure

- docerina-ui/package.json
- gradle.properties
- testerina-report-tools/package.json
> Update time-stamp versions for 2201.10.0-RC1

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/Comment.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/comment0.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/comment1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/comment2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/comment3.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/comment4.json
> Add new line to the begining of comment

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/ModelGenerator.java
> Fix statement node issue when building connections

- build.gradle
> Add sequence diagram JARs to the build

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/CodeAnalyzer.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/SuggestedModelGenerator.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/FunctionCall.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/data_mapper1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/flags1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/function_call-user1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/suggested_flow_model/config/error_handler2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/suggested_flow_model/config/if1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/suggested_flow_model/config/if2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/suggested_flow_model/config/if3.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/suggested_flow_model/config/if4.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/suggested_flow_model/config/if5.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/suggested_flow_model/config/if6.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/suggested_flow_model/config/if7.json
The PR includes the following changes:
- Added a suggested flag to nodes with branches, ensuring the suggestion outlines the entire node where applicable.
- If a function call node is not cached, the corresponding data is fetched from the central repository.
> Improve the flow model diagram

- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/function_call-user1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/visible_variable_types/config/config1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/visible_variable_types/config/config2.json
- gradle.properties
Update the Ballerina HTTP version
> Update Ballerina HTTP and IO version

- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/package_components/config/config1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/package_components/config/config2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/package_components/config/config3.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/package_components/source/source3.bal
- gradle.properties
Add test cases for the implementation: https://github.com/ballerina-platform/ballerina-lang/pull/43476
> Add test cases for the enhanced `ballerinaPackage/components` API

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/OpenApiServiceGenerator.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/java/io/ballerina/flowmodelgenerator/extension/ServiceGeneratorTest.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/openapi_service_gen/config/config4.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/openapi_service_gen/contracts/petstore1.yaml
> Remove `ballerina/lang` from the functions of OAS service

- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/java/io/ballerina/flowmodelgenerator/extension/ConfigVariablesTest.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/configurable_variables/config/config1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/configurable_variables/config/config2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/configurable_variables/config/config3.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/configurable_variables/config/config4.json
> Fix config variables related test failure

- flow-model-generator/modules/flow-model-generator-ls-extension/build.gradle
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/copilot_context/config/data_mapper6.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/copilot_context/config/data_mapper7.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/copilot_context/source/data_mapper/greetings.bal
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/package_components/config/config4.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/package_components/source/source4.bal
- gradle.properties
$title, including those in the Suggested Components API and the GitHub Copilot Context API.
> Add tests for the existing APIs

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/SourceBuilder.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/function_call-lang-lib.json
$subject
Part of [issue](https://github.com/wso2-enterprise/eggplant-project/issues/209).
> Remove adding unwanted import statements for pre-declared lang libs

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/DeleteNodeGenerator.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/If.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/delete_node/config/delete_node10.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/delete_node/config/delete_node11.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/delete_node/config/delete_node12.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/delete_node/source/delete_node6.bal
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/if.json
> Remove empty else block

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/DataMapper.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/data_mapper-main.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/data_mapper-service.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/data_mapper1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/data_mapper2.json
> Add semicolon to the data mapper function

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/ResourceActionCall.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/resource_action_call-github.json
> Fix resource access action path toSource functionality

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/DataMapper.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/java/io/ballerina/flowmodelgenerator/extension/SourceGeneratorTest.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/data_mapper-main.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/data_mapper-service.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/data_mapper1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/data_mapper2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/source/data_mapper/data_mappings.bal
> Avoid generating data mapper function if exists

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/NewConnection.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/new_connection6.json
> Skip checkError flag in new connection params

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/SuggestedModelGenerator.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/main/java/io/ballerina/flowmodelgenerator/extension/FlowModelGeneratorService.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/suggested_flow_model/config/error_handler3.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/suggested_flow_model/config/error_handler4.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/suggested_flow_model/source/error_handler/service.bal
Similar to how suggestions ignore syntax errors, this implementation also extends to overlook semantic errors.
> Disregard semantic errors in copilot suggestions

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/DeleteNodeGenerator.java
> Fix bug in delete first config

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/ConfigVariablesManager.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/NodeBuilder.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/configurable_variables/config/config1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/configurable_variables/config/config2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/configurable_variables/config/config3.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/configurable_variables/config/config5.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/configurable_variables/source/config5/Ballerina.toml
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/configurable_variables/source/config5/config.bal
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/configurable_variables/source/config5/main.bal
> Add diagnostics into config variable flow node

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/CommonUtils.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/main/java/io/ballerina/flowmodelgenerator/extension/ExpressionEditorService.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/main/java/io/ballerina/flowmodelgenerator/extension/request/ExpressionEditorDiagnosticsRequest.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/main/java/io/ballerina/flowmodelgenerator/extension/response/ExpressionEditorDiagnosticsResponse.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/java/io/ballerina/flowmodelgenerator/extension/ExpressionEditorDiagnosticsTest.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagnostics/config/single1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagnostics/config/single2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagnostics/config/single3.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagnostics/config/single4.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagnostics/config/single5.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagnostics/source/source.bal
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/testng.xml
$title with the diagnostics that are only relevant to the considered expression.
API - `expressionEditor/diagnostics`
Request - String filePath, String expression, String type, LinePosition startLine
Response - org.eclipse.lsp4j.Diagnostic diagnostics
> Introduce a new API to retrieve diagnostics for the inline expression editor

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/FunctionGenerator.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/db/DatabaseManager.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/connector1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/connector2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/resource_connector.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/get_connectors/covid.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/get_connectors/default.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/get_connectors/http.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/get_connectors/sql.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/get_functions/config/custom_default.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/get_functions/config/custom_sum.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/get_functions/config/default.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/get_functions/config/simple.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/new_connection-covid.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/new_connection-http.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/new_connection-redis.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/remote_action_call-covid-getStatusByCountry.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/remote_action_call-http-get.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/remote_action_call-http-post.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/remote_action_call-redis-get.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/remote_action_call-redis-set.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/resource_action_call-github.json
- flow-model-generator/modules/flow-model-index-generator/src/main/java/io/ballerina/indexgenerator/IndexGenerator.java
- flow-model-generator/modules/flow-model-index-generator/src/main/resources/packages.json
This PR includes the following changes:
1. Only revamped extended library modules are included.
2. All functions from the Ballerina organization are now displayed by default in the search UI.
> Update the extended packages list in the index

- flow-model-generator/modules/flow-model-generator-ls-extension/src/main/java/io/ballerina/flowmodelgenerator/extension/ExpressionEditorService.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/java/io/ballerina/flowmodelgenerator/extension/ExpressionEditorTypesTest.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/config/config3.json
$title as currently, a specific location is required; this API modification allows types to be retrieved by simply providing the project path.
> Retrieve types for a project path

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/CommonUtils.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/DataMapper.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/error_handler5.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/error_handler6.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/xml_payload.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/data_mapper-main.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/data_mapper-service.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/source/data_mapper/main.bal
This PR includes the following changes:
1. Remove the placeholder and generate a unique function name for the value field.
2. Simplify the qualified type signature by removing unnecessary names such as org and version.
> Resolve issues related to the data mapper

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/NewConnection.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/new_connection1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/new_connection7.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/new_connection8.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/new_connection9.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/source/new_connection7/Ballerina.toml
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/source/new_connection7/main.bal
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/source/new_connection7/new_connection7.bal
> Add import module statement when adding local connection

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/AvailableNodesGenerator.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/CodeAnalyzer.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/ResourceActionCall.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/connector1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/connector2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/resource_connector.json
$subject
Fixed the [#issue](https://github.com/wso2-enterprise/eggplant-project/issues/356).
https://github.com/user-attachments/assets/0bc0cc6a-d4fc-43dd-a550-b0afcd212b36
> Filter remote functions which has a resource function in http Client

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/CodeAnalyzer.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/new_connection1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/new_connection2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/new_connection3.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/remote_action_call-http-get1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/remote_action_call-http-get2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/remote_action_call-http-get3.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/resource_action_call-http-get1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/source/http_get_node.bal
$subject
Fixes [#issue](https://github.com/wso2-enterprise/eggplant-project/issues/399).
https://github.com/user-attachments/assets/db53eec1-1da5-4808-ae21-429b1714dde5
> Fix rendering flow models of  implicit new expressions and http resource invocations

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/DeleteNodeHandler.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/delete_node/config/delete_node13.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/delete_node/config/delete_node14.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/delete_node/config/delete_node15.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/delete_node/source/delete_node7.bal
$subject
This is an extend of https://github.com/ballerina-platform/ballerina-dev-tools/pull/453
> Delete empty else-if node

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/FunctionCall.java
> Fix the NPE when selecting a data mapper in the function call template

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/ConnectorGenerator.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/db/DatabaseManager.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/get_connectors/default.json
$title to allow the extensions to set the limit and the offset for the default connectors list.
> Add pagination support to the default connections list 

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/CodeAnalyzer.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/ActionCall.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/FunctionCall.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/NewConnection.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/ResourceActionCall.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/function_call-log2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/remote_action_call-http-post1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/resource_action_call-http-get1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/resource_action_call-http-post1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/source/log_source.bal
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/function_call-log-printInfo.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/function_call-log-printInfo.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/function_call-log1.json
> Fix rendering record rest fields in function call forms

- .github/workflows/build-master.yml
- .github/workflows/daily-build.yml
- .github/workflows/publish-release.yml
- .github/workflows/pull-request.yml
- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/architecturemodelgenerator/core/generators/entrypoint/FunctionEntryPointModelGenerator.java
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/ballerina/rainier/Ballerina.toml
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/ballerina/rainier/resources/Ballerina.toml
- docerina-ui/package.json
- gradle.properties
- gradle/javaProject.gradle
- testerina-report-tools/package.json
> Migrate to Java 21 and new Runtime APIs

- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/currency_converter1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/function_call-log1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/function_call-log2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/function_call-user1.json
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
> Bump the Dependencies for the Update 11 Release

- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/java/io/ballerina/flowmodelgenerator/extension/ModelGeneratorTest.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/diagnostics4.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/force_assign_function.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/function_call-json1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/source/function_call.bal
> Enable jsondata test cases in the model generator

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/EnclosedNodeFinder.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/get_enclosed_func_def/config/current_package_ref_4.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/get_enclosed_func_def/config/current_package_ref_5.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/get_enclosed_func_def/source/proj_1/services.bal
> Get the enclosed resource, remote function definition for a given position

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/FunctionGenerator.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/main/java/io/ballerina/flowmodelgenerator/extension/FlowModelGeneratorService.java
- gradle.properties
$title as the latter approach has intermittent issues (tracked with: https://github.com/ballerina-platform/ballerina-lang/issues/43695).
> Get module names directly from the module class rather than the semantic model

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/AvailableNodesGenerator.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/connector1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/connector2.json
$subject
Fixes [issue](https://github.com/wso2-enterprise/eggplant-project/issues/463)
> Suggest remote action methods for http connector methods and fix issue with provided unintended resource actions

- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/designmodelgenerator/core/DesignModelGenerator.java
- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/designmodelgenerator/core/model/Automation.java
- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/designmodelgenerator/core/model/Connection.java
- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/designmodelgenerator/core/model/Function.java
- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/designmodelgenerator/core/model/Location.java
- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/designmodelgenerator/core/model/ResourceFunction.java
- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/designmodelgenerator/core/model/Service.java
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/get_design_model/config/project_with_all_components.json
> Connection to function relationship in component diagram

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/Codedata.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/main/java/io/ballerina/flowmodelgenerator/extension/ExpressionEditorService.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/main/java/io/ballerina/flowmodelgenerator/extension/response/ExpressionEditorDiagnosticsResponse.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/java/io/ballerina/flowmodelgenerator/extension/FunctionCallTemplateTest.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_call_template/config/config5.json
The PR addresses the following issues.
1. Obtain the default module prefix if the package name contains ".".
2. Ensure the diagnostics returned by the diagnostics API are unique.
> Process the module prefix of the function call template

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/FunctionGenerator.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/Metadata.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/DataMapperBuilder.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/get_functions/config/custom_default.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/get_functions/config/custom_sum.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/data_mapper-main.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/data_mapper-service.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/source/data_mapper/types.bal
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/data_mapper-main.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/data_mapper-service.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/data_mapper1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/data_mapper2.json
> Change APIs to support top level datamapper

- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/resource_action_call_github.json
- gradle.properties
> Update lang timestamp version

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/DataMapManager.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/java/io/ballerina/flowmodelgenerator/extension/DataMappingVisualizeTest.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/data_mapper_visualize/config/variable4.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/data_mapper_visualize/config/variable5.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/data_mapper_visualize/source/proj/Ballerina.toml
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/data_mapper_visualize/source/proj/main.bal
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/data_mapper_visualize/source/proj/types.bal
> Identify visualizable fields in connections

- service-model-generator/modules/service-model-generator-ls-extension/src/main/java/io/ballerina/servicemodelgenerator/extension/ServiceModelGeneratorService.java
- service-model-generator/modules/service-model-generator-ls-extension/src/main/java/io/ballerina/servicemodelgenerator/extension/Utils.java
- service-model-generator/modules/service-model-generator-ls-extension/src/test/java/io/ballerina/servicemodelgenerator/extension/AbstractLSTest.java
- service-model-generator/modules/service-model-generator-ls-extension/src/test/java/io/ballerina/servicemodelgenerator/extension/UpdateFunctionTest.java
- service-model-generator/modules/service-model-generator-ls-extension/src/test/resources/testng.xml
- service-model-generator/modules/service-model-generator-ls-extension/src/test/resources/update_function/config/update_resource_path.json
- service-model-generator/modules/service-model-generator-ls-extension/src/test/resources/update_function/source/update_resource_path.bal
$subject
https://github.com/user-attachments/assets/f6dca9b2-1d78-4be4-983c-056d7869cd2b
> Fix not sending the text edits to update the resource function path

- service-model-generator/modules/service-model-generator-ls-extension/src/main/java/io/ballerina/servicemodelgenerator/extension/ServiceModelGeneratorConstants.java
- service-model-generator/modules/service-model-generator-ls-extension/src/main/java/io/ballerina/servicemodelgenerator/extension/ServiceModelGeneratorService.java
- service-model-generator/modules/service-model-generator-ls-extension/src/main/java/io/ballerina/servicemodelgenerator/extension/Utils.java
- service-model-generator/modules/service-model-generator-ls-extension/src/main/java/io/ballerina/servicemodelgenerator/extension/model/FunctionReturnType.java
- service-model-generator/modules/service-model-generator-ls-extension/src/main/java/io/ballerina/servicemodelgenerator/extension/model/Value.java
- service-model-generator/modules/service-model-generator-ls-extension/src/main/resources/functions/http_resource.json
- service-model-generator/modules/service-model-generator-ls-extension/src/test/java/io/ballerina/servicemodelgenerator/extension/GetHttpResourceModelTest.java
- service-model-generator/modules/service-model-generator-ls-extension/src/test/java/io/ballerina/servicemodelgenerator/extension/ServiceModelAPITests.java
- service-model-generator/modules/service-model-generator-ls-extension/src/test/java/io/ballerina/servicemodelgenerator/extension/UpdateFunctionTest.java
- service-model-generator/modules/service-model-generator-ls-extension/src/test/resources/get_http_resource_model/config/http_resource_model.json
- service-model-generator/modules/service-model-generator-ls-extension/src/test/resources/testng.xml
$subject
This PR will address following concerns
- Add the missing metadata for the resource function params
- Improve the names and descriptions of the http response type schema (Fixes [issue](https://github.com/wso2-enterprise/eggplant-project/issues/512))
- Refactor the code
> Fix usability issues in the http service model

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/DataMapManager.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/java/io/ballerina/flowmodelgenerator/extension/DataMappingSourceTest.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/data_mapper_source/config/variable14.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/data_mapper_source/source/variable13.bal
> Handle variable reference assignment in datamapper source generation

- flow-model-generator/modules/flow-model-generator-ls-extension/src/main/java/io/ballerina/flowmodelgenerator/extension/TypesManagerService.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/main/java/io/ballerina/flowmodelgenerator/extension/request/TypeUpdateRequest.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/java/io/ballerina/flowmodelgenerator/extension/typesmanager/CreateAndUpdateTypeTest.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/update_record_type3.json
> Fix NPE for filePath when creating and updating types

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/VisibleVariableTypesGenerator.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/visible_variable_types/config/config1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/visible_variable_types/config/config2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/visible_variable_types/source/data_mapper/service.bal
> Add parameters to the visible variable types API

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/DataMapManager.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/java/io/ballerina/flowmodelgenerator/extension/DataMappingSourceTest.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/data_mapper_source/config/variable15.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/data_mapper_source/config/variable16.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/data_mapper_source/config/variable17.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/data_mapper_source/source/variable14.bal
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/data_mapper_source/source/variable15.bal
> Delete array element in datamap view

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/FormBuilder.java
- flow-model-generator/modules/flow-model-generator-ls-extension/build.gradle
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/configurable_variables/config/config1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/configurable_variables/config/config2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/configurable_variables/config/config3.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/configurable_variables/config/config4.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/configurable_variables/config/config5.json
$subject
Fixes https://github.com/wso2-enterprise/eggplant-project/issues/521
> Set optional property in config variable

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/Function.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/utils/TypeTransformer.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/java/io/ballerina/flowmodelgenerator/extension/typesmanager/GetGraphqlTypeTest.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/get_service_class1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/get_service_class2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/get_service_class3.json
> Improve function schema to match with the previous implementations and fix metadata and name not found for class symbols 

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/CodeAnalyzer.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/WaitBuilder.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/wait.json
$title with the following changes:
- Added variable name and type to the form
- Fixed the key of the first future
> Fix the node template of the wait

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/TypesManager.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/NodeKind.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/utils/SourceCodeGenerator.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/utils/TypeTransformer.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/utils/TypeUtils.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/java/io/ballerina/flowmodelgenerator/extension/typesmanager/CreateAndUpdateTypeTest.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/create_intersection_type.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/create_tuple_type.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/get_all_types.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/get_error_type_def.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/get_record_type1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/get_record_type3.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/get_record_type5.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/get_union_type1.json
> Add tuple type descriptor support and enable `getAllTypes` to return all types

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/TypesManager.java
> Fix getting service declaration via `getTypes` API

- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/designmodelgenerator/core/CommonUtils.java
- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/designmodelgenerator/core/ConnectionFinder.java
- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/designmodelgenerator/core/DesignModelGenerator.java
> Fix the "No Such Element" issue in the architecture diagram

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/WaitBuilder.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/wait1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/wait2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/wait3.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/wait4.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/wait5.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/wait6.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/wait7.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/wait8.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/wait9.json
> Add variable type and name when generating the wait statement

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/TypesManager.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/java/io/ballerina/flowmodelgenerator/extension/JsonConverterTest.java
> Make linerange null for Typedata generated from record conversion

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/TypesManager.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/create_enum_type.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/create_intersection_type.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/create_table_type.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/create_tuple_type.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/create_union_type.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/get_all_types.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/source/test_pack1/types.bal
$title
e.g.
```ballerina
type Rec record {|
string:Char code; // this is an inbuilt type which is implemented in lang library
|};
```
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc …
> Ignore inbuilt types (defined in lang-libs) in references for type `typesManager` APIs

- service-model-generator/modules/service-model-generator-ls-extension/src/main/java/io/ballerina/servicemodelgenerator/extension/ServiceModelGeneratorConstants.java
- service-model-generator/modules/service-model-generator-ls-extension/src/main/java/io/ballerina/servicemodelgenerator/extension/ServiceModelGeneratorService.java
- service-model-generator/modules/service-model-generator-ls-extension/src/main/java/io/ballerina/servicemodelgenerator/extension/util/ListenerUtil.java
- service-model-generator/modules/service-model-generator-ls-extension/src/main/java/io/ballerina/servicemodelgenerator/extension/util/Utils.java
- service-model-generator/modules/service-model-generator-ls-extension/src/test/java/io/ballerina/servicemodelgenerator/extension/ServiceModelAPITests.java
$subject
New Default Listener flow
https://github.com/user-attachments/assets/e9bd3985-a836-4aba-bbbb-50a8f1747d6c
> Update selecting default listener selection flow

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/ModuleNodeAnalyzer.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/FormBuilder.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/FunctionDefinitionBuilder.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/config1.json
$title as there can be only one automation, the main function name should be read-only as it is reserved.
> Disable the editing the name of main function

- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/designmodelgenerator/core/DesignModelGenerator.java
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/get_design_model/config/project_with_all_components.json
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/get_design_model/config/project_with_nested_connection_calls.json
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/get_design_model/source/project_3/BITService.bal
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/get_design_model/source/project_3/Ballerina.toml
> Fix not showing nested function call connections in remote and resource functions

- .github/workflows/build-master.yml
- .github/workflows/daily-build.yml
- .github/workflows/publish-release.yml
- .github/workflows/pull-request.yml
- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/architecturemodelgenerator/core/generators/entrypoint/FunctionEntryPointModelGenerator.java
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/ballerina/rainier/Ballerina.toml
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/ballerina/rainier/resources/Ballerina.toml
- docerina-ui/package.json
- gradle.properties
- gradle/javaProject.gradle
- sequence-diagram-model-generator/modules/sequence-diagram-model-generator-ls-extension/src/test/resources/responses/connectorTest1.json
- sequence-diagram-model-generator/modules/sequence-diagram-model-generator-ls-extension/src/test/resources/responses/connectorTest2.json
- sequence-diagram-model-generator/modules/sequence-diagram-model-generator-ls-extension/src/test/resources/responses/connectorTest3.json
- sequence-diagram-model-generator/modules/sequence-diagram-model-generator-ls-extension/src/test/resources/responses/connectorTest4.json
- sequence-diagram-model-generator/modules/sequence-diagram-model-generator-ls-extension/src/test/resources/responses/connectorTest5.json
- testerina-report-tools/package.json
> Update dependencies for the 2201.11.0 release

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/ModuleNodeAnalyzer.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/FormBuilder.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/DataMapperDefinitionBuilder.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/FunctionDefinitionBuilder.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/data_mapper_def1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/data_mapper_def2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/data_mapper_def3.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/data_mapper_def4.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/data_mapper_def5.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/function_def1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/function_def10.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/function_def11.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/function_def12.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/function_def13.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/function_def2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/function_def3.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/function_def4.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/function_def5.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/function_def6.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/function_def7.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/function_def8.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/function_def9.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/data_mapper-main.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/data_mapper-service.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/function_definition.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/data_mapper_definition1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/data_mapper_definition4.json
With this PR, the following changes are made:
1. Removed "⇒" when editing the data mapper definition
2. Made the data mapper return type required
3. Made the function parameters optional
> Make minor improvements to the function definition forms

- .github/workflows/build-master.yml
- .github/workflows/daily-build.yml
- .github/workflows/pull-request.yml
$title due to https://github.com/ballerina-platform/ballerina-library/issues/7581
> Downgrade the Ballerina distribution version used for pulling the modules

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/converters/JsonToRecordMapper.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/main/java/io/ballerina/flowmodelgenerator/extension/JsonToRecordConverterService.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/main/java/io/ballerina/flowmodelgenerator/extension/XMLToRecordConverterService.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/java/io/ballerina/flowmodelgenerator/extension/JsonConverterTest.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/java/io/ballerina/flowmodelgenerator/extension/XMLConverterTest.java
> Change json conversion API names

- gradle.properties
> Bump ballerina version to 2201.12.0-20250220-175300-0350e62b

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/CodeAnalyzer.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/error_handler3.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/remote_action_call-http-get2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/remote_action_call-http-get3.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/remote_action_call-http-post2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/remote_action_call-http-post3.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/wait3.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/wait4.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/wait5.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/wait6.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/wait8.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/while5.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/suggested_flow_model/config/error_handler1.json
$title.
https://github.com/user-attachments/assets/66338874-a456-4d0f-a4c9-8a134e3fa0c6
> Avoid visiting the expression in the return statement

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/expressioneditor/Debouncer.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/expressioneditor/ExpressionEditorContext.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/expressioneditor/services/DebouncedExpressionEditorRequest.java
> Fix intermittent errors in the expression editor-related services

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/SourceGenerator.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/data_mapper-main.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/data_mapper-service.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/data_mapper2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/data_mapper_definition2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/data_mapper_definition3.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/data_mapper_definition5.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/function_definition.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/new_connection10.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/new_connection9.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/source/new_connection8/Ballerina.toml
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/source/new_connection8/connections.bal
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/source/new_connection8/main.bal
Fixes https://github.com/wso2-enterprise/eggplant-project/issues/642
> Add new line for a new source genration

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/expressioneditor/services/ExpressionDiagnosticsRequest.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagnostics/config/variable2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagnostics/source/main.bal
$title as we are currently only prioritizing errors.
> Remove warnings from the diagnostics generated for the expression properties

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/utils/TypeTransformer.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/get_all_types.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/get_class.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/get_object_type.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/get_service_class1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/get_service_class2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/get_service_class3.json
$title
The resource function kind must be sent as `RESOURCE` and remote function kind as `REMOTE`
> Link to the PR for changes to …
> Fix getting remote/resource function kind as FUNCTION

- flow-model-generator/modules/flow-model-generator-ls-extension/src/main/java/io/ballerina/flowmodelgenerator/extension/InitializerService.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/main/java/io/ballerina/flowmodelgenerator/extension/request/CreateFilesRequest.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/main/java/io/ballerina/flowmodelgenerator/extension/response/CreateFilesResponse.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/main/resources/META-INF/services/org.ballerinalang.langserver.commons.service.spi.ExtendedLanguageServerService
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/java/io/ballerina/flowmodelgenerator/extension/InitializerTest.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/initializer/config/config1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/initializer/config/config2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/initializer/source/proj1/Ballerina.toml
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/initializer/source/proj1/main.bal
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/initializer/source/proj2/Ballerina.toml
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/initializer/source/proj2/main.bal
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/testng.xml
$subject
We can add tasks that need to be run initially.
Here we have created the necessary files.
> Add service to initialize tasks

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/SourceBuilder.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/error_handler5.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/error_handler6.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/function_call-json-toJson.json
$title
Fixes https://github.com/wso2-enterprise/eggplant-project/issues/659
> Link to the PR for changes to the training content …
> Fix erroneous type name resolving in source builder

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/utils/SourceCodeGenerator.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/utils/TypeTransformer.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/get_all_types.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/get_array_type_def.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/get_class.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/get_enum_type1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/get_enum_type2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/get_error_type_def.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/get_object_type.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/get_record_type1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/get_record_type2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/get_record_type3.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/get_record_type4.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/get_record_type5.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/get_service_class1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/get_service_class2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/get_service_class3.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/get_table_type_def.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/get_union_type1.json
Fixes part of https://github.com/wso2-enterprise/eggplant-project/issues/503
> Link to the PR for changes to the training content …
> Change editable to false in name property in type-data and refactor code-generation logic

- build.gradle
- gradle.properties
- service-model-generator/modules/service-model-generator-ls-extension/build.gradle
- service-model-generator/modules/service-model-generator-ls-extension/src/main/java/io/ballerina/servicemodelgenerator/extension/ServiceModelGeneratorConstants.java
- service-model-generator/modules/service-model-generator-ls-extension/src/main/java/io/ballerina/servicemodelgenerator/extension/ServiceModelGeneratorService.java
- service-model-generator/modules/service-model-generator-ls-extension/src/main/java/io/ballerina/servicemodelgenerator/extension/model/Value.java
- service-model-generator/modules/service-model-generator-ls-extension/src/main/java/io/ballerina/servicemodelgenerator/extension/util/ListenerUtil.java
- service-model-generator/modules/service-model-generator-ls-extension/src/main/java/io/ballerina/servicemodelgenerator/extension/util/ServiceClassUtil.java
- service-model-generator/modules/service-model-generator-ls-extension/src/main/java/io/ballerina/servicemodelgenerator/extension/util/Utils.java
- service-model-generator/modules/service-model-generator-ls-extension/src/main/resources/listeners/tcp.json
- service-model-generator/modules/service-model-generator-ls-extension/src/main/resources/services/tcp.json
- service-model-generator/modules/service-model-generator-ls-extension/src/test/resources/add_service/config/add_tcp_service.json
- service-model-generator/modules/service-model-generator-ls-extension/src/test/resources/get_sm_from_source/config/tcp_service_model.json
- service-model-generator/modules/service-model-generator-ls-extension/src/test/resources/get_sm_from_source/source/sample7/tcp.bal
$subject
Fixes [#issue](https://github.com/wso2-enterprise/eggplant-project/issues/711)
https://github.com/user-attachments/assets/f9971b70-457a-45e9-9aff-018927b95890
> Support add/view/edit TCP services

- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/data_mapper_types/config/function_call1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/data_mapper_types/config/function_call2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/data_mapper_types/config/variable1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/data_mapper_types/config/variable2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/resource_action_call_github.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/record_config/config/config1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/record_config/config/config2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/visible_variable_types/config/config1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/visible_variable_types/config/config2.json
- gradle.properties
> Update lang version

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/TypesGenerator.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/config/config1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/config/config2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/config/config3.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/config/config4.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/config/config5.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/config/config6.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/config/config7.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/config/config8.json
> Improve the categorization in the types API

- flow-model-generator/modules/flow-model-generator-ls-extension/src/main/java/io/ballerina/flowmodelgenerator/extension/FlowModelGeneratorService.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/main/java/io/ballerina/flowmodelgenerator/extension/request/SearchRequest.java
> Update search request to use queryMap

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/TypesGenerator.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/config/config1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/config/config4.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/config/config7.json
> Rename the "Built-in union types" category to "Other types"

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/AvailableNodesGenerator.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/java/io/ballerina/flowmodelgenerator/extension/agentsmanager/AvailableNodesTest.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/config/available_agents.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/source/agent_4/Ballerina.toml
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/source/agent_4/agents.bal
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/source/agent_4/main.bal
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/source/agent_4/service.bal
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/source/agent_4/types.bal
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/connector2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/connector3.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/force_assign.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/foreach1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/function1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/function2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/function3.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/lock1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/match1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/match2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/method1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/on_fail_clause1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/resource_connector.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/transaction1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/transaction2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/while1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/testng.xml
> Add agent catagory

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/AgentCallBuilder.java
> Fix issue in Agent run source gen

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/CodeAnalyzer.java
> Support to edit Agent

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/AgentCallBuilder.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/CallBuilder.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/config/agent_call_template.json
> Fix issue in agent call node template

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/ModelGenerator.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/java/io/ballerina/flowmodelgenerator/extension/ModuleNodesTest.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/module_nodes/config/agent_model.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/module_nodes/source/agent/Ballerina.toml
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/module_nodes/source/agent/agents.bal
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/module_nodes/source/agent/connections.bal
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/module_nodes/source/agent/main.bal
> Fix agent node template

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/AgentsGenerator.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/CodeAnalyzer.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/AgentBuilder.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/ClassInitBuilder.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/java/io/ballerina/flowmodelgenerator/extension/agentsmanager/GetToolsTest.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/config/agent_call_template.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/config/agent_template.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/config/function_tool.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/config/get_tools.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/config/model_template.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/config/remote_action_tool.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/config/remote_action_tool2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/config/remote_action_tool3.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/source/agent_1/Ballerina.toml
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/source/agent_1/main.bal
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/testng.xml
> Fix several issues in Agent

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/NPFunctionDefinitionBuilder.java
- model-generator-commons/src/main/java/io/ballerina/modelgenerator/commons/CommonUtils.java
> Update natural programming library checking logic

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/AgentsGenerator.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/config/remote_action_tool2.json
> Add connection name to generate AI tool

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/NodeTemplateGenerator.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/NodeBuilder.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/CallBuilder.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/NewConnectionBuilder.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/ResourceActionCallBuilder.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/main/java/io/ballerina/flowmodelgenerator/extension/FlowModelGeneratorService.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/package_components/config/config1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/package_components/config/config2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/package_components/config/config3.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/package_components/config/config4.json
- gradle.properties
- model-generator-commons/src/main/java/io/ballerina/modelgenerator/commons/FunctionDataBuilder.java
- model-generator-commons/src/main/java/io/ballerina/modelgenerator/commons/ModuleInfo.java
- model-generator-commons/src/main/java/io/ballerina/modelgenerator/commons/PackageUtil.java
$title after checking if the module exists in the local central cache.
https://github.com/user-attachments/assets/c951dbe2-60c0-4523-8269-22d7b494f75e
> Send the pull module notification

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/AgentsGenerator.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/java/io/ballerina/flowmodelgenerator/extension/agentsmanager/GenToolsTest.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/config/remote_action_tool4.json
> Handle target type in AI tool generation

- architecture-model-generator/modules/architecture-model-generator-core/build.gradle
- architecture-model-generator/modules/architecture-model-generator-ls-extension/build.gradle
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/main/java/io/ballerina/designmodelgenerator/extension/DesignModelGeneratorService.java
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/java/io/ballerina/designmodelgenerator/extension/DesignModelGeneratorTest.java
$title, as the loadProject in the workspace manager does not properly resolve the dependencies. This is a temporary solution until the root cause is found.
> Compile the project via the package loader at startup

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/CodeAnalyzer.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/CallBuilder.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/new_connection-rabbitmq.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/new_connection-rabbitmq.json
Preserve the order in which the function parameters are positioned.
> Fix the invalid order of the parameters in the new connection

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/TypesManager.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/main/java/io/ballerina/flowmodelgenerator/extension/TypesManagerService.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/main/java/io/ballerina/flowmodelgenerator/extension/request/MultipleTypeUpdateRequest.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/main/java/io/ballerina/flowmodelgenerator/extension/response/MultipleTypeUpdateResponse.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/java/io/ballerina/flowmodelgenerator/extension/typesmanager/CreateMultipleTypesTest.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/testng.xml
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/create_multiple_types_with_array_of_types.json
Fixes https://github.com/wso2-enterprise/eggplant-project/issues/804 …
> Add create-type support for array of type data via Types API

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/CallBuilder.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/method_call_redis_close.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/method_call_user.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/remote_action_call-azure_cosmosdb-createDocument.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/remote_action_call-covid-getStatusByCountry.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/remote_action_call-http-get.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/remote_action_call-http-post.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/remote_action_call-mysql-query.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/remote_action_call-mysql-queryRow.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/remote_action_call-redis-get.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/remote_action_call-redis-set.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/remote_action_call-snowflake-query.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/resource_action_call-docusign.dsadmin-get.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/resource_action_call-github.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/resource_action_call-http-get.json
$title as this was incorrectly set to identifier
> Change connection type to expression in action calls

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/CodeAnalyzer.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/config/agent_call_flow_node.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/source/agent_3/agents.bal
> Change the representation of icon path

- .gitignore
> Fix commit issue in the release workflow

- .github/workflows/publish-release.yml
$title due to https://github.com/ballerina-platform/ballerina-lang/issues/43816
> Downgrade the ballerina version in the publish release workflow

- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/java/io/ballerina/flowmodelgenerator/extension/ModelGeneratorTest.java
> Disable failing test cases due to version mismatch

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/AgentBuilder.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/ClassInitBuilder.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/config/agent_call_template.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/config/agent_template.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/config/model_template.json
> Get random variable names for agent

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/CodeAnalyzer.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/config/agent_call_flow_node.json
> Show tools when display annotation is not available

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/CodeAnalyzer.java
> Handle args to create agent diagram

- gradle.properties
> Bump the Ballerina lang version

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/CallBuilder.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/NPFunctionCall.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/function_call-userType.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/source/data_mapper/main.bal
- model-generator-commons/src/main/java/io/ballerina/modelgenerator/commons/FunctionDataBuilder.java
- model-generator-commons/src/main/java/io/ballerina/modelgenerator/commons/ModuleInfo.java
$title as this leads to invalid diagnostics in the subsequent calls.
> Remove the module prefix from local types

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/AgentsGenerator.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/AvailableNodesGenerator.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/SourceBuilder.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/AgentBuilder.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/config/agent_call_flow_node.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/config/remote_action_tool.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/config/remote_action_tool2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/config/remote_action_tool4.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/connector1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/connector2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/connector3.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/force_assign.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/foreach1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/function1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/function2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/function3.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/lock1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/match1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/match2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/method1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/on_fail_clause1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/resource_connector.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/transaction1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/transaction2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/while1.json
> Add more improvements to agent

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/AvailableNodesGenerator.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/ResourceActionCallBuilder.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/main/java/io/ballerina/flowmodelgenerator/extension/FlowModelGeneratorService.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/connector1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/connector2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/connector3.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/resource_connector.json
> Make OAS client available

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/expressioneditor/ExpressionEditorContext.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/completions/config/non_existence.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/completions/config/proj2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/completions/config/proj3.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/completions/config/proj7.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/completions/config/proj9.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/completions/source/proj/types.bal
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagnostics/config/variable3.json
The template statement has been updated from `var` to `any|error` to support more expression types in these nodes
> Support any and error expressions in the variable and return nodes

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/AvailableNodesGenerator.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/AgentBuilder.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/java/io/ballerina/flowmodelgenerator/extension/AvailableNodesTest.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/connector1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/connector2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/connector3.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/force_assign.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/foreach1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/function1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/function2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/function3.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/lock1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/match1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/match2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/method1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/on_fail_clause1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/resource_connector.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/transaction1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/transaction2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/while1.json
> Make agent node available

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/analyzers/function/ModuleNodeAnalyzer.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/NPFunctionDefinitionBuilder.java
This is a hack for now, need to fix the pulling the module properly in a generic way. [Related issue](https://github.com/wso2-enterprise/eggplant-project/issues/8663)
> Brief description of the new feature or bug fix …
> Add module pulling for np module and add line-range for prompt parameter

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/AgentsGenerator.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/SourceBuilder.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/AgentBuilder.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/config/function_tool.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/config/get_tools.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/source/agent_1/main.bal
> Add more improvements to the agent

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/OpenAPIClientGenerator.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/main/java/io/ballerina/flowmodelgenerator/extension/OpenAPIService.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/main/java/io/ballerina/flowmodelgenerator/extension/request/OpenAPIGeneratedModulesRequest.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/main/java/io/ballerina/flowmodelgenerator/extension/response/OpenAPIGeneratedModulesResponse.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/java/io/ballerina/flowmodelgenerator/extension/OpenApiClientGeneratorTest.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/openapi_client_gen/config/config1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/openapi_client_gen/config/config2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/openapi_client_gen/config/config3.json
> Add API to get avialble generated OAS modules

- flow-model-generator/modules/flow-model-central-client/src/main/java/io/ballerina/centralconnector/CentralAPI.java
- flow-model-generator/modules/flow-model-central-client/src/main/java/io/ballerina/centralconnector/RemoteCentral.java
- flow-model-generator/modules/flow-model-central-client/src/main/java/io/ballerina/centralconnector/RestClient.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/AvailableNodesGenerator.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/NPFunctionDefinitionBuilder.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/java/io/ballerina/flowmodelgenerator/extension/AvailableNodesTest.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/connector1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/connector2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/connector3.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/force_assign.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/foreach1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/function1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/function2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/function3.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/lock1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/match1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/match2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/method1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/on_fail_clause1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/resource_connector.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/transaction1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/transaction2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/while1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/new_connection-datalake.json
- model-generator-commons/build.gradle
- model-generator-commons/src/main/java/io/ballerina/modelgenerator/commons/FunctionDataBuilder.java
- model-generator-commons/src/main/java/module-info.java
If the version is not set, it will fetch the latest version available for the given Ballerina version.
> Extend support for pulling modules that have no version

- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/lang_lib-array-lastIndexOf.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/lang_lib-array-map.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/lang_lib-array-reduce.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/lang_lib-error-detail.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/lang_lib-map-reduce.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/lang_lib-stream-reduce.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/lang_lib-table-reduce.json
- flow-model-generator/modules/flow-model-index-generator/src/main/java/io/ballerina/indexgenerator/DatabaseManager.java
- flow-model-generator/modules/flow-model-index-generator/src/main/java/io/ballerina/indexgenerator/IndexGenerator.java
The type parameters are replaced with the respective referred type
> Fix the type constraints of lang lib libraries 

- build.gradle
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/DataMapperDefinitionBuilder.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/data_mapper_def1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/data_mapper_def2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/data_mapper_def3.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/data_mapper_def4.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/data_mapper_def5.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/data_mapper-main.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/data_mapper-service.json
$title, as currently only records are shown.
> Change the type constraint of the data mapper to `anydata` 

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/NPFunctionCall.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/utils/TypeTransformer.java
Fixes https://github.com/wso2-enterprise/eggplant-project/issues/869 …
> Fixes for Types API and NP module change

- service-model-generator/modules/service-model-generator-ls-extension/src/main/java/io/ballerina/servicemodelgenerator/extension/model/Parameter.java
- service-model-generator/modules/service-model-generator-ls-extension/src/main/java/io/ballerina/servicemodelgenerator/extension/model/Value.java
- service-model-generator/modules/service-model-generator-ls-extension/src/test/resources/get_sm_from_source/config/graphql_service_with_single_listener.json
- service-model-generator/modules/service-model-generator-ls-extension/src/test/resources/get_sm_from_source/config/http_service_with_anonymous_listener.json
- service-model-generator/modules/service-model-generator-ls-extension/src/test/resources/get_sm_from_source/config/http_service_with_multiple_listeners.json
- service-model-generator/modules/service-model-generator-ls-extension/src/test/resources/get_sm_from_source/config/http_service_with_single_listener.json
- service-model-generator/modules/service-model-generator-ls-extension/src/test/resources/service_class_model_from_source/config/service_class_model_from_source1.json
- service-model-generator/modules/service-model-generator-ls-extension/src/test/resources/service_class_model_from_source/config/service_class_model_from_source2.json
$subject
Fixes [#issue](https://github.com/wso2-enterprise/eggplant-project/issues/886)
https://github.com/user-attachments/assets/601b1bf0-7d41-4f53-b95f-9435e517b0ac
> Set enable true for param type schema

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/TypesManager.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/main/java/io/ballerina/flowmodelgenerator/extension/TypesManagerService.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/java/io/ballerina/flowmodelgenerator/extension/typesmanager/GetGraphqlTypeTest.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/get_gql_service_class_with_annotation.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/source/test_pack2/graphql_service.bal
$title
fixes https://github.com/wso2-enterprise/eggplant-project/issues/901
> Link to the PR for changes to the training content …
> Fix graphql service not retrieving with annotations attached

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/AgentsGenerator.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/main/java/io/ballerina/flowmodelgenerator/extension/AgentsManagerService.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/config/function_tool.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/source/agent_1/types.bal
> Add isolated keyword to generate AI tool

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/converters/utils/JsonToRecordMapperConverterUtils.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/main/java/io/ballerina/flowmodelgenerator/extension/FlowModelGeneratorService.java
- model-generator-commons/src/main/java/io/ballerina/modelgenerator/commons/PackageUtil.java
> Obtain the semantic model via the package compilation

- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/designmodelgenerator/core/CodeAnalyzer.java
- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/designmodelgenerator/core/ConnectionFinder.java
- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/designmodelgenerator/core/DesignModelGenerator.java
- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/designmodelgenerator/core/IntermediateModel.java
- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/designmodelgenerator/core/model/Connection.java
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/get_design_model/config/ai_agent_connections.json
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/get_design_model/source/project_4/Ballerina.toml
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/get_design_model/source/project_4/chatAgent.bal
> Draw connections in agents

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/AvailableNodesGenerator.java
> Set the correct module name for OAS generated connectors

- gradle.properties
> Prepare for release

- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/java/io/ballerina/flowmodelgenerator/extension/ModelGeneratorTest.java
> Disable the test cases to related to redis version mismatch

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/CodeAnalyzer.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/ClassInitBuilder.java
> Add model type enum to model edit path

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/type/RecordValueGenerator.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/record_value_gen/config/config1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/record_value_gen/config/config10.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/record_value_gen/config/config3.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/record_value_gen/config/config4.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/record_value_gen/config/config5.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/record_value_gen/config/config6.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/record_value_gen/config/config7.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/record_value_gen/config/config8.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/record_value_gen/config/config9.json
$subject
Fixes [#issue_1](https://github.com/wso2-enterprise/eggplant-project/issues/926)
https://github.com/user-attachments/assets/f263c5fd-dbab-4ddb-ba8c-11eef5cfdf99
Fixes [#issue_2](https://github.com/wso2/product-ballerina-integrator/issues/14)
https://github.com/user-attachments/assets/fddfacd3-43cb-444d-aa79-8ec94ad05f00
> Add indentation for text generated from record value generator and Fix issue with generating value for union types

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/CodeAnalyzer.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/resource_action_call_github.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/source/github_resource_call.bal
$subject
Fixes [#issue](https://github.com/wso2-enterprise/vscode-extensions/issues/5192)
https://github.com/user-attachments/assets/6c40d5da-b2bb-45f8-a1da-44df57019886
> Fix path params not showing in the flow diagram form in edit mode

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/AvailableNodesGenerator.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/ResourceActionCallBuilder.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/connector1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/connector2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/connector3.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/resource_connector.json
- model-generator-commons/src/main/java/io/ballerina/modelgenerator/commons/FunctionDataBuilder.java
> Remove isGenerated flag from OAS node template generation

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/TypesGenerator.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/config/config1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/config/config4.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/config/config5.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/config/config6.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/config/config7.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types/config/non_existence.json
$title 
Fixes https://github.com/wso2/product-ballerina-integrator/issues/56
> Add string[] to the type helper pane

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/DataMapManager.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/java/io/ballerina/flowmodelgenerator/extension/DataMappingModelTest.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/data_mapper_model/config/query1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/data_mapper_model/config/query2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/data_mapper_model/config/variable19.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/data_mapper_model/config/variable20.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/data_mapper_model/source/query1.bal
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/data_mapper_model/source/query2.bal
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/data_mapper_query_convert/config/variable2.json
> Generate mappings for query

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/type/RecordValueGenerator.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/record_value_gen/config/config1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/record_value_gen/config/config11.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/record_value_gen/config/config4.json
$subject
https://github.com/user-attachments/assets/42f3c06b-eadb-486d-a14e-644d69c99fdf
> Fix issue with generate record field value generation in Record Editor View

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/AgentsGenerator.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/CodeAnalyzer.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/ClassInitBuilder.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/main/java/io/ballerina/flowmodelgenerator/extension/AgentsManagerService.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/main/java/io/ballerina/flowmodelgenerator/extension/request/GetAllMemoryManagersRequest.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/main/java/io/ballerina/flowmodelgenerator/extension/response/GetMemoryManagersResponse.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/java/io/ballerina/flowmodelgenerator/extension/agentsmanager/FlowNodeGeneratorTest.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/java/io/ballerina/flowmodelgenerator/extension/agentsmanager/GetAllMemoryManagersTest.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/java/io/ballerina/flowmodelgenerator/extension/agentsmanager/SourceGeneratorTest.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/config/agent_call_flow_node_1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/config/agent_call_flow_node_2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/config/get_all_memory_managers.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/config/memory_manager_source.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/config/memory_manager_template.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/config/model_template.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/config/source.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/source/agent_5/Ballerina.toml
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/source/agent_5/agents.bal
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/source/agent_5/main.bal
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/source/agent_5/service.bal
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/source/agent_5/types.bal
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/testng.xml
- model-generator-commons/src/main/java/io/ballerina/modelgenerator/commons/FunctionData.java
- model-generator-commons/src/main/java/io/ballerina/modelgenerator/commons/FunctionDataBuilder.java
> Support for memory manager of agent

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/utils/FlowNodeUtil.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/function_call-user9.json
> Add support for function calls with no parameters

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/analyzers/function/ModuleNodeAnalyzer.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/FormBuilder.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/Property.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/FunctionDefinitionBuilder.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/function_def1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/function_def10.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/function_def11.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/function_def13.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/function_def14.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/function_def3.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/function_def4.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/function_def5.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/function_def6.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/function_def7.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/function_def8.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/function_def9.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/source/function_def/functions.bal
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/function_definition.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/np_functions/np_function_definition.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/function_definition14.json
> Add description support to function definition

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/ConfigVariablesManager.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/main/java/io/ballerina/flowmodelgenerator/extension/ConfigEditorService.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/configurable_variables_update/config/config5.json
$subject. 
Fixes https://github.com/wso2/product-ballerina-integrator/issues/79 …
> Fix updating values of config variables defined outside config.bal

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/utils/SourceCodeGenerator.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/utils/TypeTransformer.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/java/io/ballerina/flowmodelgenerator/extension/typesmanager/CreateAndUpdateTypeTest.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/java/io/ballerina/flowmodelgenerator/extension/typesmanager/GetAllTypesTest.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/create_array_type1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/create_array_type2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/create_array_type3.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/get_all_types1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/get_all_types2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/get_array_type_def.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/get_error_type_def.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/get_record_type1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/get_record_type3.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/get_record_type5.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/source/test_pack3/types.bal
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/xml_converter/config/config2.json
> Add array-size support for array types

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/CodeAnalyzer.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/java/io/ballerina/flowmodelgenerator/extension/agentsmanager/FlowNodeGeneratorTest.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/config/agent_call_flow_node_3.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/source/agent_6/Ballerina.toml
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/source/agent_6/agents.bal
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/source/agent_6/main.bal
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/source/agent_6/service.bal
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/source/agent_6/types.bal
> Add default memory manager to the model

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/ConfigVariablesManager.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/main/java/io/ballerina/flowmodelgenerator/extension/ConfigEditorService.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/configurable_variables_update/config/config5.json
$subject. 
Previously all the new config variables were added to the top of the `config.bal` file. With this change, they will now be appended to the last line of the file instead.
Related to https://github.com/wso2/product-ballerina-integrator/issues/79
> Link(s) to product …
> Fix insertion position of new config variables 

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/analyzers/function/ModuleNodeAnalyzer.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/FormBuilder.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/Property.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/FunctionDefinitionBuilder.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/function_def1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/function_def10.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/function_def11.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/function_def14.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/function_def15.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/function_def2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/function_def3.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/function_def4.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/function_def6.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/function_def7.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/function_def8.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/function_def9.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/source/function_def/functions.bal
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/function_definition.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/function_definition15.json
> Add description to function return

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/AgentsGenerator.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/agents_manager/config/function_tool.json
> Fix tool generation without description

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/SourceGenerator.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/update_connection-redis.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/source/update_connection-redis/Ballerina.toml
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/source/update_connection-redis/connections.bal
$subject
https://github.com/user-attachments/assets/3632a40e-ed61-432c-aedb-3ff3d8f1107c
> Fix issue with updating module level flow model nodes

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/SourceBuilder.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/FunctionDefinitionBuilder.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/function_definition16.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/function_definition17.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/function_definition18.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/to_source/config/function_definition19.json
> Handle function document generation

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/TypesManager.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/utils/SourceCodeGenerator.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/java/io/ballerina/flowmodelgenerator/extension/typesmanager/CreateAndUpdateTypeTest.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/java/io/ballerina/flowmodelgenerator/extension/typesmanager/GetGraphqlTypeTest.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/create_array_type4.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/create_graphql_class_type2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/get_gql_service_class1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/get_gql_service_class_with_annotation.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/get_service_class1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/get_service_class2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/get_service_class3.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/get_union_type1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/source/test_pack2/graphql_service.bal
Fixes https://github.com/wso2/product-ballerina-integrator/issues/83
Fixes https://github.com/wso2/product-ballerina-integrator/issues/133
Fixes Cannot adding service classes with union with enum types
> Link(s) to product documentation that addresses the changes of this PR. If no doc …
> Fix multiple issues with types API

- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/diagnostics1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/config/variable8.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagram_generator/source/new_data.bal
- model-generator-commons/src/main/java/io/ballerina/modelgenerator/commons/CommonUtils.java
> Change "$CompilationError$" to "UnknownType" in the type form

- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/artifactsgenerator/ModuleNodeTransformer.java
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/artifacts/config/connection.json
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/artifacts/config/tcp.json
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/artifacts/config/type.json
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/artifacts/source/type.bal
$title 
Fixes https://github.com/wso2/product-ballerina-integrator/issues/138
> Add enum types and classes to the project tree view

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/expressioneditor/services/IdentifierDiagnosticsRequest.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagnostics/config/module_identifier10.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/diagnostics/config/module_identifier11.json
$title
Fixes https://github.com/wso2/product-ballerina-integrator/issues/129
> Remove the invalid redeclaration diagnostic when editing an existing variable

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/SourceBuilder.java
> Generate agent tools in agent.bal

- .github/workflows/build-master.yml
- .github/workflows/daily-build.yml
- .github/workflows/publish-release.yml
- .github/workflows/pull-request.yml
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/java/io/ballerina/designmodelgenerator/extension/ArtifactsTest.java
- gradle.properties
> Bump the ballerina lang timestamp version

- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/artifactsgenerator/Artifact.java
- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/artifactsgenerator/ModuleNodeTransformer.java
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/main/java/io/ballerina/designmodelgenerator/extension/DesignModelGeneratorService.java
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/main/java/io/ballerina/designmodelgenerator/extension/PublishArtifactsSubscriber.java
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/main/java/io/ballerina/designmodelgenerator/extension/response/ArtifactsParams.java
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/java/io/ballerina/designmodelgenerator/extension/PublishArtifactsSubscriberTest.java
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/artifacts/config/graphql.json
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/artifacts/config/http_service.json
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/artifacts/config/kafka.json
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/artifacts/config/project.json
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/artifacts/config/rabbitmq.json
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/artifacts/config/tcp.json
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/artifacts/source/graphql.bal
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/publish_artifacts/config/main.json
The PR addresses the following changes.
- Include the project path in the responses so the frontend can identify which projects have changed.
- Improve the service name
- Run the artifacts API only when changes occur.
Part of https://github.com/wso2/product-ballerina-integrator/issues/154
> Improve the project tree view APIs 

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/TypesManager.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/Member.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/utils/SourceCodeGenerator.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/java/io/ballerina/flowmodelgenerator/extension/typesmanager/CreateAndUpdateTypeTest.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/create_record_type_with_imports.json
- model-generator-commons/src/main/java/io/ballerina/modelgenerator/commons/CommonUtils.java
> Add import statement support for types API updating types

- service-model-generator/modules/service-model-generator-ls-extension/src/main/resources/services/http.json
- service-model-generator/modules/service-model-generator-ls-extension/src/test/resources/get_service_model/config/http_service_model_1.json
- service-model-generator/modules/service-model-generator-ls-extension/src/test/resources/get_service_model/config/http_service_model_2.json
Reverts ballerina-platform/ballerina-dev-tools#809
> Revert "Remove `greetings` resource creation when adding a HTTP service"

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/Function.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/utils/SourceCodeGenerator.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/java/io/ballerina/flowmodelgenerator/extension/typesmanager/CreateGraphqlClassTypeTest.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/types_manager/config/create_graphql_class_type_with_imports.json
> Add support for imports in functions in service classes in types

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/VisibleVariableTypesGenerator.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/expressioneditor/ExpressionEditorContext.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/expressioneditor/services/ExpressionDiagnosticsRequest.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/expressioneditor/services/LvExpressionDiagnosticRequest.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/visible_variable_types/config/config1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/visible_variable_types/config/config2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/visible_variable_types/config/config3.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/visible_variable_types/source/data_mapper/clone.bal
The PR makes the following changes:
1. Fixes the issue of having module variables to the local variable
2. Re-enabled module variables and removed object types
3. Fixes issues where diagnostics from different files are produced in the diagnostics API
Fixes https://github.com/wso2/product-ballerina-integrator/issues/166
> Improve the diagnostics and expression helper in the expression editor

- service-model-generator/modules/service-model-generator-ls-extension/src/main/java/io/ballerina/servicemodelgenerator/extension/util/ServiceClassUtil.java
- service-model-generator/modules/service-model-generator-ls-extension/src/main/java/io/ballerina/servicemodelgenerator/extension/util/ServiceModelUtils.java
- service-model-generator/modules/service-model-generator-ls-extension/src/main/java/io/ballerina/servicemodelgenerator/extension/util/Utils.java
- service-model-generator/modules/service-model-generator-ls-extension/src/main/resources/functions/object_default.json
- service-model-generator/modules/service-model-generator-ls-extension/src/main/resources/functions/object_init.json
- service-model-generator/modules/service-model-generator-ls-extension/src/main/resources/functions/object_remote.json
- service-model-generator/modules/service-model-generator-ls-extension/src/main/resources/functions/object_resource.json
- service-model-generator/modules/service-model-generator-ls-extension/src/test/resources/add_service/config/add_http_service.json
- service-model-generator/modules/service-model-generator-ls-extension/src/test/resources/get_sm_from_source/config/github_service_model.json
- service-model-generator/modules/service-model-generator-ls-extension/src/test/resources/get_sm_from_source/config/kafka_service_model.json
- service-model-generator/modules/service-model-generator-ls-extension/src/test/resources/get_sm_from_source/config/rabbitmq_service_model.json
- service-model-generator/modules/service-model-generator-ls-extension/src/test/resources/get_sm_from_source/config/tcp_service_model.json
- service-model-generator/modules/service-model-generator-ls-extension/src/test/resources/service_class_model_from_source/config/service_class_model_from_source1.json
- service-model-generator/modules/service-model-generator-ls-extension/src/test/resources/service_class_model_from_source/config/service_class_model_from_source2.json
$subject
Fixes [#issue](https://github.com/wso2/product-ballerina-integrator/issues/158)
This PR will provide these fixes
- Remove return statement from the `greetings` resource generated in the add http service operation
- Update the `valueTypeConstrain` of service class name
- Disable functions edit and delete of event and file triggers
- Enable a disabled param schema in service type function adding form
> Minor improvements related to the service designers

- gradle.properties
> Bump versions for 2.3.0 release

- architecture-model-generator/modules/architecture-model-generator-ls-extension/build.gradle
> Add test dependencies to architecture model

- architecture-model-generator/modules/architecture-model-generator-ls-extension/build.gradle
Reverts ballerina-platform/ballerina-dev-tools#819
> Revert "Add test dependencies to architecture model"

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/SourceBuilder.java
> Fix issue in node generation in tool

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/search/FunctionSearchCommand.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/search/config/functions/custom_sum.json
$title, as we require this information to open the node form for call functions
Fixes https://github.com/wso2/product-ballerina-integrator/issues/185
> Add org and package name to the local functions

- model-generator-commons/src/main/java/io/ballerina/modelgenerator/commons/CommonUtils.java
> Fix issue in OAS client module import for AI tool

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/analyzers/function/ModuleNodeAnalyzer.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/FormBuilder.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/Property.java
- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/node/FunctionDefinitionBuilder.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/function_def14.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/function_def15.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/function_definition/config/function_def7.json
> Preserve isolated keyword and annotations

- gradle.properties
> Bump version for release

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/model/SourceBuilder.java
$subject
https://github.com/user-attachments/assets/9bcdb5d2-ffba-47cd-88e9-17790fb14765
> Fix inline agent creation issue

- model-generator-commons/src/main/java/io/ballerina/modelgenerator/commons/PackageUtil.java
> Fix intermittent issues in the compilation

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/AvailableNodesGenerator.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/caller.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/resource_connector.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/source/caller.bal
> Add connections in the parameters to the node palette

- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/node_template/config/remote_action_call-rabbitmq-basicAck.json
- model-generator-commons/src/main/java/io/ballerina/modelgenerator/commons/FunctionDataBuilder.java
$title since these are the only connectors currently indexed in the package index. This restriction will be removed when the package index is deprecated.
> Search only for connectors named "Client" in the index

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/AvailableNodesGenerator.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/config/inside_nested_foreach.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/available_nodes/source/inside_nested_foreach.bal
Fixes issue464 : [https://github.com/wso2-enterprise/eggplant-project/issues/464](https://github.com/wso2-enterprise/eggplant-project/issues/464)
> Fixes : The break and continue statements are not visible within the if condition #464

- flow-model-generator/modules/flow-model-generator-ls-extension/src/main/java/io/ballerina/flowmodelgenerator/extension/JsonToRecordConverterService.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/main/java/io/ballerina/flowmodelgenerator/extension/XMLToRecordConverterService.java
$title
2201.12.x PR: https://github.com/ballerina-platform/ballerina-dev-tools/pull/855
Fixes https://github.com/wso2/ballerina-vscode/issues/610
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why …
> [main] Fix not getting created record from JSON and XML without types.bal Fix types bal main

- flow-model-generator/modules/flow-model-generator-ls-extension/src/main/java/io/ballerina/flowmodelgenerator/extension/JsonToRecordConverterService.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/main/java/io/ballerina/flowmodelgenerator/extension/XMLToRecordConverterService.java
$title
Fixes https://github.com/wso2/ballerina-vscode/issues/610 …
> [2201.12.x] Fix not getting created record from JSON and XML without types.bal

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/OpenAPIClientGenerator.java
- gradle.properties
> $Subject
Fixes: https://github.com/ballerina-platform/ballerina-library/issues/7806
> Enable flatten and align for client generation

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/OpenAPIClientGenerator.java
- gradle.properties
> $Subject
Part of: https://github.com/ballerina-platform/ballerina-library/issues/7806
> [2201.12.x] Enable flatten and align for client generation

- gradle.properties
> [2201.12.x] Update OpenAPI core stable version

- gradle.properties
> Bump version for 2201.12.4 release

- flow-model-generator/modules/flow-model-index-generator/src/main/resources/packages.json
$subject
Fixes [The Record Config generates an invalid result for the Twilio connector ](https://github.com/wso2/product-ballerina-integrator/issues/416)
> Re-generate the flow model index with update twillio version

- flow-model-generator/modules/flow-model-generator-core/src/main/java/io/ballerina/flowmodelgenerator/core/VisibleVariableTypesGenerator.java
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/visible_variable_types/config/config1.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/visible_variable_types/config/config2.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/visible_variable_types/config/config3.json
- flow-model-generator/modules/flow-model-generator-ls-extension/src/test/resources/visible_variable_types/config/non_existence.json
> Include only the type name in the Type object for visibleVariableTypes API variable types

- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/designmodelgenerator/core/CodeAnalyzer.java
- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/designmodelgenerator/core/CommonUtils.java
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/get_design_model/config/ai_agent_connections.json
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/get_design_model/config/http_service_project.json
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/get_design_model/config/imported_listeners.json
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/get_design_model/config/project_with_nested_connection_calls.json
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/get_design_model/config/project_with_private_methods.json
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/get_design_model/source/project_6/Ballerina.toml
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/get_design_model/source/project_6/main.bal
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/get_design_model/source/project_6/types.bal
$subject
Fixes [issue](https://github.com/wso2/product-ballerina-integrator/issues/402)
> Fix issue in showing resource path in design model

- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/designmodelgenerator/core/CodeAnalyzer.java
- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/designmodelgenerator/core/CommonUtils.java
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/get_design_model/config/ai_agent_connections.json
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/get_design_model/config/http_service_project.json
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/get_design_model/config/imported_listeners.json
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/get_design_model/config/project_with_nested_connection_calls.json
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/get_design_model/config/project_with_private_methods.json
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/get_design_model/source/project_6/Ballerina.toml
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/get_design_model/source/project_6/main.bal
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/get_design_model/source/project_6/types.bal
$subject
Fixes [issue](https://github.com/wso2/product-ballerina-integrator/issues/402)
Duplicate of #875
> [2201.12.x] Fix issue in showing resource path in design model

- architecture-model-generator/modules/architecture-model-generator-core/src/main/java/io/ballerina/designmodelgenerator/core/ConnectionFinder.java
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/get_design_model/config/imported_listeners.json
- architecture-model-generator/modules/architecture-model-generator-ls-extension/src/test/resources/get_design_model/source/project_2/BITService.bal
$subject
Fixes [issue](https://github.com/wso2/product-ballerina-integrator/issues/550)
> Fix NPE in getDesignModel api
